### PR TITLE
PEN-1422: [SM] | Black border displaying on .socialBtn-container class when no social is present

### PR DESCRIPTION
**Pull request by vinnie-olsen**
## Description
Modified `footer-block` so that social container doesn't render a border when no social site properties are configured.

## Jira Ticket
- [PEN-1422](https://arcpublishing.atlassian.net/browse/PEN-1422)

## Acceptance Criteria
Social icon container no longer displays a border (appearing as a "dot" when collapsed and no child content) when a site has no social site properties configured in their `blocks.json`.

## Test Steps
1. In `Fusion-News-Theme` repo, checkout `master` & `git pull`
2. In `Fusion-News-Theme/blocks.json` - under `the-gazette` `siteProperties`, set `facebookPage`, `twitterUsername` and `rssUrl` to blank strings
3. After checking out this feature branch in `fusion-news-theme-blocks`, run `rm -rf ./node_modules && npx lerna clean && npm i && npx lerna bootstrap && cd blocks/header-nav-chain-block && npm i && cd ../..`
4. Run `npx fusion start -f -l @wpmedia/footer-block` in `Fusion-News-Theme`
5. Open http://localhost/pf/homepage/?_website=the-sun , scroll down to the footer and you should see all social button/links in the site primary color with a border surrounding the entire button group
6. Open http://localhost/pf/homepage/?_website=the-gazette , scroll down to the footer and you should see no social buttons and no "dot"/border remaining on the collapsed social container. Contrast with the example from the ticket http://shawmedia-shaw-media-sandbox.cdn.arcpublishing.com/ where you can see a small "dot" in the footer (which is the container border)

### Before
When the current site has no `facebookPage`, `twitterUsername` or `rssUrl` properties setup in `blocks.json` for the current site, a small "dot"/border would display inside the footer section

### After
When the current site has no `facebookPage`, `twitterUsername` or `rssUrl` properties setup in `blocks.json` for the current site, **no** "dot"/border displays inside the footer section

## Dependencies or Side Effects
Add to `siteProperties` for `the-gazette` (in `blocks.json`):
- `"facebookPage": ""`
- `"twitterUsername": ""`
- `"rssUrl": ""`

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps above are working
- [ ] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by beltrancaliz** [comment]
@vinnie-olsen do we have any tests for this?

**Comment by vinnie-olsen** [comment]
@beltrancaliz since this is just a bug fix applying only to the `border` style and making sure it's not visible, I didn't think any additional tests were needed. I didn't see any other testing that verified individual style values. Do you think this is something that should be expanded upon in the unit tests?

**Comment by beltrancaliz** [comment]
> @beltrancaliz since this is just a bug fix applying only to the `border` style and making sure it's not visible, I didn't think any additional tests were needed. I didn't see any other testing that verified individual style values. Do you think this is something that should be expanded upon in the unit tests?

it could be worth adding a test case on the footer for when no social icons are present

**Comment by vinnie-olsen** [comment]
@beltrancaliz gotcha sounds good! I'll write up a test case or two for that 👍

**Comment by vinnie-olsen** [comment]
@beltrancaliz added a test case for when there's no social site props setup 👍

**Review by beltrancaliz — APPROVED** [review]
Great job @vinnie-olsen !

**Pull request merged**
