### PR TITLE
Themes 1208

### PR DESCRIPTION
**Pull request by malavikakoppula**
## Description

After converting the feature pack to themes V2, some fonts need to have updated to a primary font (Inter). 

- Overline

- Section title links 

## Jira Ticket

- [THEMES-1208](https://arcpublishing.atlassian.net/browse/THEMES-1208)

## Acceptance Criteria

**Actual Behavior**

The overline and the section title links have font primary as (Times) on desktop and mobile
**Expected Behavior**

The overline and the section title links primary font (Inter)

## Test Steps

1. Checkout this branch `git checkout {THEMES-1208}`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/section-title-block`
3. Inspect and check for links and overline font-family

## Dependencies or Side Effects

- Components pr for local development: https://github.com/WPMedia/arc-themes-components/pull/197

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-1208]: https://arcpublishing.atlassian.net/browse/THEMES-1208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by blakeganderson — CHANGES_REQUESTED** [review]
@malavikakoppula  the section title looks good, and both blocks look good in storybook, but When I run the code locally I'm still seeing the overline with a font-family of Times

**Comment by malavikakoppula** [comment]
> @malavikakoppula the section title looks good, and both blocks look good in storybook, but When I run the code locally I'm still seeing the overline with a font-family of Times

@blakeganderson, Your local means the PB local?

**Comment by blakeganderson** [comment]
> @malavikakoppula ye

**Comment by blakeganderson** [comment]
> 

@malavikakoppula yes, Is there going to be a companion overline component update for this ticket?

**Comment by malavikakoppula** [comment]
> > 
> 
> @malavikakoppula yes, Is there going to be a companion overline component update for this ticket?

@blakeganderson I am still working on that part. This PR was not ready for review. Will update in the dependencies section. Thank you

**Comment by blakeganderson** [comment]
> > > 
> > 
> > 
> > @malavikakoppula yes, Is there going to be a companion overline component update for this ticket?
> 
> @blakeganderson I am still working on that part. This PR was not ready for review. Will update in the dependencies section. Thank you

Got it, In that case this PR should be good to go!

**Review by blakeganderson — APPROVED** [review]
LGTM 👍

**Comment by pardistaherzadeh** [comment]
LGTM. Ready to be merged.

**Pull request merged**
