### PR TITLE
Ads UAT fixes, refactoring & clean-up (removed 'lodash.get' dependency)

### PR DESCRIPTION
**Pull request by vinnie-olsen**
## Description
UAT FIXES: Fix for `leaderboard_large` ad breakpoints, fix and refactoring of `pos` targeting functionality, removed `lodash.get` dependency, other clean-up and refactoring.

## Jira Ticket
This branch contains fixes for issues cited on:
- [PEN-425](https://arcpublishing.atlassian.net/browse/PEN-425)
- [PEN-436](https://arcpublishing.atlassian.net/browse/PEN-436)
- [PEN-1223](https://arcpublishing.atlassian.net/browse/PEN-1223)

## Acceptance Criteria
_copy from ticket_

## Test Steps
1. In `Fusion-News-Theme` repo, checkout `master` & `git pull`
2. After checking out this feature branch in `fusion-news-theme-blocks`, run `rm -rf ./node_modules && npx lerna clean && npm i && npx lerna bootstrap && cd blocks/header-nav-chain-block && npm i && cd ../..`
3. Run `npx fusion start -f -l @wpmedia/header-nav-chain-block` in `Fusion-News-Theme`
4. Open 'Homepage' in PB editor, Chrome DevTools `Network` tab and filter by `dfp`. You should see that there are no requests being made to DFP when viewing page in PB Admin.
5. In PB editor, make sure two instances of `Google Ad` feature with a type of `leaderboard_large` are added to the page. Then stage & publish.
6. Open http://localhost/pf/homepage/?_website=the-sun in a new tab
7. Open Chrome DevTools `Network` tab and filter by `dfp`
8. Find the request for the `leaderboard_large` ad call
image
9. You should see the `prev_iu_szs` param set to `970x250|970x90|728x90`
10. Now look through the rest of the requests under `Network` with `dfp` filter. Look at the `pos` value for each ad unit (under `prev_scp` query string param) and it should match the `position` value. Specifically take a look at the two `leaderboard_large` requests. The first one should have a `pos` of `1` and the second one should have a `pos` of `2`.

### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
None

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [X] Confirmed all the test steps above are working
- [X] Confirmed there are no linter errors
- [X] Confirmed this PR has reasonable code coverage
  - [X] Confirmed this PR has unit test files
  - [X] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [X] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Review by JackHowa — APPROVED** [review]
Really good work here!

**Comment by vinnie-olsen** [comment]
Thanks @JackHowa ! 🙂

**Comment by JackHowa** [comment]
no worries, sorry this pr got missed earlier. this is deployed to cc

**Comment by vinnie-olsen** [comment]
No worries at all and much appreciated!

**Pull request merged**
