### PR TITLE
Pen tmedia-6: remove hardcoded font urls

### PR DESCRIPTION
**Pull request by brentmiller1973**
## Description
This removes the hardcoded font urls and strictly relies on the fontUrl to be present in blocks.json.  Also this ticket concerns changes made to the theme API where fontUrl will be an array of font urls, instead of a just a string:  https://github.com/WPMedia/themebuilder-api/pull/75.  To keep backwards compatibility, an inspection of the fontUrl value is checked to see if its an array or string and then processed accordingly.

## Jira Ticket
https://arcpublishing.atlassian.net/browse/TMEDIA-6

## Acceptance Criteria
Remove the site specific logic
If a site has a `fontUrl` set in their properties the correct font stylesheet is loaded

## Test Steps
1) Pull the latest master from Fusion-News-Theme.  Note the changes to the blocks.json (fontUrl property).
2) Run this branch locally
3) Create a page and publish.
4) View the published page for a site that is setting the fontUrl and confirm the font url is in the header and the fonts are showing up on the elements.

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x ] Confirmed all the test steps a reviewer will follow above are working. 
- [x ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x ] Confirmed this PR has unit test files
  - [x ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist 
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr. 
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by matthewroach** [comment]
@visionbegin Can you update the blocks.json in the Fusion News Theme repo (https://github.com/WPMedia/Fusion-News-Theme) to not cause a regression in font's not loading for existing test cases?

**Comment by brentmiller1973** [comment]
> @visionbegin Can you update the blocks.json in the Fusion News Theme repo (https://github.com/WPMedia/Fusion-News-Theme) to not cause a regression in font's not loading for existing test cases?

@matthewroach Good point.  Updated master branch.

**Comment by matthewroach** [comment]
@visionbegin Code looks good - can we add test coverage to make the GitHub action happy

**Comment by brentmiller1973** [comment]
> @visionbegin Code looks good - can we add test coverage to make the GitHub action happy

@matthewroach All clear now. Added a test case to check for fontUrl link

**Review by matthewroach — APPROVED** [review]
Looks good to me, thanks for updating the test.

**Pull request merged**
