### PR TITLE
Tmedia 787 news theme

### PR DESCRIPTION
**Pull request by JackHowa**
## Description

- Use news theme from commerce theme

## Jira Ticket

- [TMEDIA-787](https://arcpublishing.atlassian.net/browse/TMEDIA-787)

## Acceptance Criteria

Match commerce theme

## Test Steps

1. Checkout this branch `git checkout TMEDIA-787-news-theme`
2. Run storybook and see components styled `npm run storybook` in news theme

### Before

- no news styling for components

### After

- specific styling for nested components in theme

## Dependencies or Side Effects

feature pack pr https://github.com/WPMedia/arc-themes-feature-pack/pull/247

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by matthewroach** [comment]
@JackHowa - The video block is not showing the video with the base theme applied

**Comment by JackHowa** [comment]
Gotcha looking. 

Looks like the fallback is actually being set ... 

Oh I see height is not being set in-line
Screen Shot 2022-05-17 at 09 37 27

**Comment by nschubach** [comment]
> Gotcha looking.
> 
> Looks like the fallback is actually being set ...
> 
> Oh I see height is not being set in-line Screen Shot 2022-05-17 at 09 37 27

The --height is defaulted to 65 in the CSS
image

**Comment by JackHowa** [comment]
ok here we go. the media item is display flex not block. 
Screen Shot 2022-05-17 at 09 57 09

----

looks like the height is 0 with padding bottom in the powa container css actually vs the themes components. and that padding bottom is being set because the height of the page is 0

Screen Shot 2022-05-17 at 09 46 27
 
Screen Shot 2022-05-17 at 09 52 50
Screen Shot 2022-05-17 at 09 54 23

**Comment by JackHowa** [comment]
@matthewroach updated with stretch items

**Review by matthewroach — APPROVED** [review]

**Pull request merged**
