### PR TITLE
Fix/asub 8199 regwall safari

### PR DESCRIPTION
**Pull request by accbjt**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description

This is a small fix for Safari where the RegWall button is hidden below the toolbar. This only effects Safari and. no other browser.

## Jira Ticket

- [ASUB-8199](https://arcpublishing.atlassian.net/browse/ASUB-8199)

## Acceptance Criteria

Registration Wall should be above the fold on Safari and Chrome

## Test Steps
- Create a page with the Paywall block
- Add the RegWall
- You will need to comment some code and return only the RegWall in the paywall theme block. This will allow you to see the RegWall without any logic to trigger a showing of the RegWall.
```
	return (
		<RegwallOffer
			actionText={registerActionText}
			actionUrl={registerActionUrl}
			displayMode={displayMode}
			headlineText={registerHeaderText}
			linkPrompt={payLinkPrompt}
			linkText={linkText}
			linkUrl={linkUrl}
			reasonPrompt={registerReasonPrompt}
			subheadlineText={registerSubHeaderText}
			className={BLOCK_CLASS_NAME}
		/>
	);
```
- You will need to either open the Paywall page on a iPhone device using the IP address or you can open it in the Xcode simulator. You can only test Chrome on a mobile device.

### Before
Screenshot 2024-03-14 at 7 28 18 PM

### After
Screenshot 2024-03-14 at 7 28 18 PM

IMG_60E0869E7B74-1

## Dependencies or Side Effects

_Examples of dependencies or side effects are:_

- Manifest pr for new block:
- Feature pack pr for local development:
- How to deploy to news: https://arcpublishing.atlassian.net/wiki/spaces/TI/pages/3138682964/News+Theme+2.0+Migration+Development+Deployment+Notes
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Dependency on another PR that needs to be merged first

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[ASUB-8199]: https://arcpublishing.atlassian.net/browse/ASUB-8199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by vgalatro** [comment]
@accbjt , is there a site with the regwall setup I can set my local instance to for testing this?

**Comment by vgalatro** [comment]
@accbjt , just checking again, is this ready for review? Could you add testing instructions, and preferably which environment to use locally that has a regwall already setup.

**Comment by accbjt** [comment]
> @accbjt , just checking again, is this ready for review? Could you add testing instructions, and preferably which environment to use locally that has a regwall already setup.

@vgalatro I need to make an update to this. I think this issue might also be on mobile chrome. We don't have a regwall setup yet but I will add one to subssinglesite. I''ll let you know once I have that ready for you and I'll add testing instructions.

**Comment by vgalatro** [comment]
This will need to go into 2.3.0 once the branch is created, as we're launching 2.2.1 soon with security hotfixes.

**Comment by accbjt** [comment]
@vgalatro I added test steps for this. The RegWall is a little tricky so I added some steps to test it locally.

**Pull request closed without merging**
