### PR TITLE
Tbrands 88 font style mobile increase 

### PR DESCRIPTION
**Pull request by JackHowa**
## Description

Update mobile font sizes for aliases

## Jira Ticket

- [TBRANDS-88](https://arcpublishing.atlassian.net/browse/TBRANDS-88)

## Acceptance Criteria

All components/blocks using mobile font body text styles updated to point to new scale

## Test Steps

1. Compare chromatic changes in the checks below
2. Ensure that the change was 2px for each increase with the alias pointing to the correct variables 

Note: for news, one of the font sizes had already been updated

### Before

Less readable small text

### After

More readable small text

## Dependencies or Side Effects

- Other prs need to include:

feature pack: https://github.com/WPMedia/arc-themes-feature-pack/pull/310
feature pack https://github.com/WPMedia/arc-themes-feature-pack/pull/309
components: https://github.com/WPMedia/arc-themes-components/pull/123

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress. -> na
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added. -> na

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by matthewroach — APPROVED** [review]

**Comment by JackHowa** [comment]
update: can't update chromatic because I'm not a reviewer 😿 

---
Will merge when I get to a computer. Can't approve sb on a phone

**Comment by JackHowa** [comment]
oh, did we want @haganka to look at this pending the change? is she still away?

**Comment by JackHowa** [comment]
It looks like commerce chromatic is not being watched 🤔

**Comment by JackHowa** [comment]
@haganka relevant commerce changes

Screen Shot 2022-07-26 at 10 34 28
https://5f91e4721ccaba0022a10782-fyyafrnfiw.chromatic.com/?path=/story/blocks-video-player--alert-title-and-description
video title update for commerce 


description font size update for commerce in hero 
Screen Shot 2022-07-26 at 10 19 00

https://5f91e4721ccaba0022a10782-fyyafrnfiw.chromatic.com/?path=/story/blocks-hero--show-overlay-center

**Comment by JackHowa** [comment]
Kelly says approved in comment https://arcpublishing.atlassian.net/browse/TBRANDS-88?focusedCommentId=785030&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-785030

**Pull request merged**
