### PR TITLE
PEN-1459 handle live video checkbox

### PR DESCRIPTION
**Pull request by amyerz**
## Description
- Resend new PR to follow up @JackHowa 's comment on https://github.com/WPMedia/fusion-news-theme-blocks/pull/546 
- update the live customfields from checkbox to text input
- if input box is empty, live label should not be shown
- handle previous checkbox value ` true` to display the preset value ('LIVE VIDEO')

## Jira Ticket
- [PEN-1459](https://arcpublishing.atlassian.net/browse/PEN-1459)

## Acceptance Criteria
On the Video Promo Block, remove the existing Live boolean Custom Field, and instead implement a string (text) custom field called Alert badge 

If a value is entered in this field, that exact text should appear above the video (aligned left), using the label specs in the Zeplin designs (using the Danger red color, which is also used for the Alert Bar) 

Note – the text should render exactly as it is input into the Custom Field – don’t automatically capitalize it or anything like that

If no value is entered in this field, then the Alert badge should not appear at all

## Test Steps
1. on the theme repo, update .env file:
- [ ] link your local engine-theme-sdk, e.g. ENGINE_SDK_REPO={PATH/TO/LOCAL/engine-theme-sdk}
- [ ] add videoOrg=prod
- [ ] add videoOrg=corecomponents

update environment/index.json
- [ ] add `"videoEnv": "prod"`

2. under block repo
create a new page and add video promo block

3. test the `Live` customfield, if no value is entered, the label should not be shown

4. entered a sample value to the `Live` field, the text should match on the label without any capitalization etc
Screen Shot 2020-11-06 at 11 00 21 AM

### Before
- `Live` customfield is a checkbox:
Screen Shot 2020-11-06 at 2 29 02 PM

### After
- `Live` customfield updated to text input box
Screen Shot 2020-11-06 at 11 00 31 AM

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps above are working
- [ ] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
@amyerz are there changes that I need to link with engine theme sdk? or is the canary version ok? 

` link your local engine-theme-sdk, e.g. ENGINE_SDK_REPO={PATH/TO/LOCAL/engine-theme-sdk}`

**Comment by JackHowa** [comment]
only changes to video-promo-block, so running `npx fusion start -f -l @wpmedia/video-promo-block`. in the future, can you add that to the test instructions?

**Comment by JackHowa** [comment]
I'm confused. we're adding videoOrg twice? in news theme environment folder I see videoOrg corecomponents 

```
 add videoOrg=prod
 add videoOrg=corecomponents

**Review by JackHowa — CHANGES_REQUESTED** [review]
This label should be called  Alert Badge not 'Live', per the requirements: 

On the Video Promo Block, remove the existing Live boolean Custom Field, and instead implement a string (text) custom field called Alert badge 

Screen Shot 2020-11-13 at 10 53 22

**Comment by JackHowa** [comment]
Also when I add an id `94ecbd60-7288-4baf-b3ec-ab563e95406a` to the content-api, I don't see any video. can you tell me in the test instructions how to show an image
Screen Shot 2020-11-13 at 10 55 45

**Comment by amyerz** [comment]
> @amyerz are there changes that I need to link with engine theme sdk? or is the canary version ok?
> 
> ` link your local engine-theme-sdk, e.g. ENGINE_SDK_REPO={PATH/TO/LOCAL/engine-theme-sdk}`

existing canary sdk is fine on this one :-)

**Comment by amyerz** [comment]
> I'm confused. we're adding videoOrg twice? in news theme environment folder I see videoOrg corecomponents
> 
> ```
>  add videoOrg=prod
>  add videoOrg=corecomponents
> ```

use `videoOrg=corecomponents` only. sorry for the confusion~

**Comment by amyerz** [comment]
> This label should be called Alert Badge not 'Live', per the requirements:
> 
> On the Video Promo Block, remove the existing Live boolean Custom Field, and instead implement a string (text) custom field called Alert badge
> 
> Screen Shot 2020-11-13 at 10 53 22

updated to Alert Badge
Screen Shot 2020-11-13 at 5 55 15 PM

**Comment by amyerz** [comment]
> Also when I add an id `94ecbd60-7288-4baf-b3ec-ab563e95406a` to the content-api, I don't see any video. can you tell me in the test instructions how to show an image
> Screen Shot 2020-11-13 at 10 55 45

looks like the customfields still have the old values. (should no longer show UUID) 
once you input the id, it should under content source, click on the 'update' button to show. 
Can you try to cd to `blocks/video-promo-block` and run `npm i` once and rebuild on the theme repo again?
The updated fields are
Screen Shot 2020-11-13 at 6 00 14 PM

**Review by JackHowa — CHANGES_REQUESTED** [review]
still unable to replicate locally

**Review by JackHowa — CHANGES_REQUESTED** [review]
Turns out, there were fusion-news-theme environment dependencies for this pr. Amy is updating instructions here and adding a pr against fusion-news-theme as well

**Review by JackHowa — CHANGES_REQUESTED** [review]
Turns out, there were fusion-news-theme environment dependencies for this pr. Amy is updating instructions here and adding a pr against fusion-news-theme as well

**Comment by amyerz** [comment]
Update instructions:
1. under the fusion-news-theme repo, add the followings to the `.env` file:
`videoOrg=prod`
`videoOrg=corecomponents`
and link to your local engine-sdk-theme repo
`ENGINE_SDK_REPO={local-path}/blocks/engine-theme-sdk`

2. under  fusion-news-theme repo, update `environment/index.json`
update/ add `  "videoEnv": "prod",`

**Comment by JackHowa** [comment]
@amyerz can you add a pr against fusion-news-theme as well? 

it should include changes to documentation for the readme `.env` as well as the environment/index.json file

**Comment by amyerz** [comment]
PR for theme repo: https://github.com/WPMedia/Fusion-News-Theme/pull/139

**Comment by amyerz** [comment]
README updated: https://github.com/WPMedia/fusion-news-theme-blocks/pull/553/commits/f4ed17e8f0be7d195df72e83b75e8abce2dc9a6c

**Review by JackHowa — APPROVED** [review]

**Pull request merged**
