### PR TITLE
TMEDIA-724 - Update logo alignment issues and right placement items

### PR DESCRIPTION
**Pull request by matthewroach**
## Description

Update Logo and right navigation items being in the correct location as per testing feedback

## Jira Ticket

- [TMEDIA-724](https://arcpublishing.atlassian.net/browse/TMEDIA-724)

## Test Steps

1. Checkout this branch `git checkout TMEDIA-724-testing-feedback`
2. Checkout branch on Feature pack `TMEDIA-724-testing-feedback`
3. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/header-nav-chain-block`
4. Test Header Nav Chain on Page with different logo placements (Left & Center)
5. Test with right components on desktop via Custom Fields

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by JackHowa — APPROVED** [review]
looks good based on the feedback

**Comment by JackHowa** [comment]
Design qa? or straight in?

**Review by malavikakoppula — APPROVED** [review]
LGTM

**Comment by matthewroach** [comment]
Was already design QA'd - this was issues found in QA

**Pull request merged**
