### PR TITLE
SENG-65 added video promo block

### PR DESCRIPTION
**Pull request by chenghsinw**
## Description
Added video promo block

## Jira Ticket
- https://arcpublishing.atlassian.net/browse/SENG-65

## Acceptance Criteria
PageBuilder users can configure a video (either VOD or Livestream) to appear on their homepage (or similar landing pages). They can also configure:
- Title
- Description
- LIVE toggle
- Autoplay

## Test Steps
1. This change is depending on this SDK PR https://github.com/WPMedia/engine-theme-sdk/pull/94
2. Add a new env variable `videoEnv` required for powa player (see below example)
3. In local env, link the SDK and the block then run local Fusion (ex https://github.com/WPMedia/Fusion-News-Theme/commit/ca61f84d0ce669b6e0849b3d3c6b92559bca3c3c)
4. Add the Video Promo block
5. Confgiure the video with content source (need to fetch video type item) or specify an available video UUID
6. Add title and description
7. Verify the video and content are showing up 

### Before
Doesn't exist

### After
screencast 2020-09-23 17-41-33

## Dependencies or Side Effects
https://github.com/WPMedia/engine-theme-sdk/pull/94

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps above are working
- [x] Confirmed there are no linter errors
- [x] Confirmed this PR has reasonable code coverage
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
Updated and added a comment for engine sdk https://github.com/WPMedia/engine-theme-sdk/pull/95

- Can you fill out the checklists in the pr template?

**Comment by chenghsinw** [comment]
@JackHowa there are tons of test case failure in the canary branch where I branched from (I just checked again). Who are suppose to fix them? 
These are from `header-nav-chain-block` and `masthead-block` blocks.

**Comment by JackHowa** [comment]
@chenghsinw huh interesting. I don't see any test case failures. As a sanity check, can you run: `rm -rf node_modules/ && npm i && npx lerna clean -y && npm t`  https://github.com/WPMedia/fusion-news-theme-blocks/blob/stable/News%20Theme%20Development.md#troubleshooting-dependencies

```
Test Suites: 99 passed, 99 total
Tests:       1 skipped, 834 passed, 835 total
Snapshots:   2 passed, 2 total
Time:        25.88s, estimated 42s

**Comment by chenghsinw** [comment]
@JackHowa, hmm interesting, that works now.

**Comment by chenghsinw** [comment]
Another question, where should I add the documentation?

**Comment by JackHowa** [comment]
@chenghsinw in the block readme -- thanks https://github.com/WPMedia/fusion-news-theme-blocks/pull/459/files#diff-050018daa08db5b0c05bc54494b10180R1

**Review by JackHowa — APPROVED** [review]
Looks good. I'd also recommend highlighting this new .env variable `Add a new env variable videoEnv required for powa player (see below example)`

**Comment by chenghsinw** [comment]
@JackHowa the documentation is added (including the new env variable part as well)

**Comment by JackHowa** [comment]
if there's nothing else I can merge and then qa can test out with canary blocks? the blocks repo deploys on push to canary branch

**Pull request merged**
