### PR TITLE
Themes 919 image height fix

### PR DESCRIPTION
**Pull request by malavikakoppula**
## Description

- Promo images do not have have a set height/width and therefore are maintaining the aspect ratio of the original 
- This applies to both desktop and mobile 

## Jira Ticket

- [THEMES-919](https://arcpublishing.atlassian.net/browse/THEMES-919)

## Acceptance Criteria
https://arcpublishing.atlassian.net/browse/THEMES-919?focusedCommentId=859672

## Test Steps

1. Checkout this branch git checkout `THEMES-919-image-height-fix`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/results-list-block,@wpmedia/search-results-list-block`
3. Add block and make following changes

    website: Gazette
    content source: content-api-collections
    _id: CK2T4JQW5JFIFH4YDM5CNQAKPA

4. click update to see the results.

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-919]: https://arcpublishing.atlassian.net/browse/THEMES-919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by matthewroach — CHANGES_REQUESTED** [review]
@malavikakoppula - I don't believe this addresses the issue outline in the ticket comments, changing the aspect ratio will not always adjust the image correctly. From the comment in the ticket we need to apply the `smart: true` option to the resizer options prop of the image component, example here - https://github.com/WPMedia/arc-themes-blocks/blob/31a616f4d67dbf85645949a0517c2dc041c79070/blocks/card-list-block/features/card-list/default.jsx#L171

**Comment by malavikakoppula** [comment]
> @malavikakoppula - I don't believe this addresses the issue outline in the ticket comments, changing the aspect ratio will not always adjust the image correctly. From the comment in the ticket we need to apply the `smart: true` option to the resizer options prop of the image component, example here -
> 
> https://github.com/WPMedia/arc-themes-blocks/blob/31a616f4d67dbf85645949a0517c2dc041c79070/blocks/card-list-block/features/card-list/default.jsx#L171

@matthewroach , Thank you. Added `smart: true`

**Review by matthewroach — CHANGES_REQUESTED** [review]
@malavikakoppula - The images are not loading now for results list as width and height are required when using the `smart` option. The issue is due to the `imageRatio` variable is undefined, there should be a default value assigned to this variable

**Comment by malavikakoppula** [comment]
> f630952



> @malavikakoppula - The images are not loading now for results list as width and height are required when using the `smart` option. The issue is due to the `imageRatio` variable is undefined, there should be a default value assigned to this variable

@matthewroach, added static height to the image [f630952](https://github.com/WPMedia/arc-themes-blocks/pull/1601/commits/f6309522dac9b9748612150d124ed710a1400f5b)

**Comment by matthewroach** [comment]
> > [f630952](https://github.com/WPMedia/arc-themes-blocks/commit/f6309522dac9b9748612150d124ed710a1400f5b)
> 
> > @malavikakoppula - The images are not loading now for results list as width and height are required when using the `smart` option. The issue is due to the `imageRatio` variable is undefined, there should be a default value assigned to this variable
> 
> @matthewroach, added static height to the image [f630952](https://github.com/WPMedia/arc-themes-blocks/pull/1601/commits/f6309522dac9b9748612150d124ed710a1400f5b)

@malavikakoppula Adding a static height will not work with the aspect ratio. We should only be passing one of the size values (width or height) to the Image component when you are passing the aspect ratio. We need to ensure the aspect ratio has a default value to account for an `undefined` scenario

**Comment by malavikakoppula** [comment]
> 

@matthewroach, Removed ImageRatio [57abc0b](https://github.com/WPMedia/arc-themes-blocks/pull/1601/commits/57abc0b3e4b9461466e2287bed648ba37188d05c)

**Review by matthewroach — APPROVED** [review]

**Pull request merged**
