### PR TITLE
PEN-670 - Update card list to not have image links in tab sequence

### PR DESCRIPTION
**Pull request by matthewroach**
## Description

Update to the card list block (missed in previous PR) to not have image links within the tab sequence

Related PR - https://github.com/WPMedia/fusion-news-theme-blocks/pull/725

## Jira Ticket
- [PEN-670](https://arcpublishing.atlassian.net/browse/PEN-670)

## Acceptance Criteria

Screen reader should read the available articles as heading links only. For instance, "Apex Legends’ Season 4 trailer provides few answers......" heading level 2 link

## Test Steps

1. Checkout this branch `git checkout PEN-670-card-list`
2. In Fusion repo run with `npx fusion start -f -l @wpmedia/card-list-block`
3. Navigate to test page - http://localhost/all-blocks/?_website=the-gazette
4. Using your keyboard tab though the page - focusing on the Card List block on the right hand side
5. Verify only the headlines are focused and not the image links

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [X] Confirmed all the test steps a reviewer will follow above are working. 
- [X] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [X] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [X] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [X] Confirmed this PR has unit test files
  - [X] Ran `npm run test`, made sure all tests are passing
  - [X] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [X] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist 
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr. 
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by vinnie-olsen** [comment]
@matthewroach I'm having some trouble getting this to start up with `npx fusion start -f -l @wpmedia/card-list-block` 🤔  Have you seen this error before? I'm getting it after trying with and without linking SDK locally. I did a search across `fusion-news-theme-blocks`, `engine-theme-sdk`, and `news-theme-css` and I can't even figure out where `block-internal-spacing` is defined 😕  I see it being included but can't find the mixin definition anywhere
image

**Comment by matthewroach** [comment]
@vinnie-olsen I just ran this branch with the linked block and didn't get the issue you are seeing. 🤔  If you want to catch up when online today we can take a look

**Review by JackHowa — APPROVED** [review]
nice work

**Comment by vinnie-olsen** [comment]
Thanks for reviewing @JackHowa 🙂  Not sure what's going on with my local with that error above 🤷‍♂️

**Pull request merged**
