### PR TITLE
Small improvement: Refactor change direct state mutation

### PR DESCRIPTION
**Pull request by JackHowa**
Apply here as well moving forward #1284

### CODE REVIEW

**Comment by nschubach** [comment]
I'm getting errors on this branch in storybook... I thought the chromatic might have been in error, but it looks like those are all valid issues?
image

**Comment by JackHowa** [comment]
@nschubach guessing the error comes from this conflict
Screen Shot 2022-04-05 at 15 44 23

**Comment by JackHowa** [comment]
oh this was the fix from Matthew for fallbacks https://github.com/WPMedia/arc-themes-blocks/pull/1299

**Review by nschubach — APPROVED** [review]

**Comment by JackHowa** [comment]
this is tracked in https://arcpublishing.atlassian.net/browse/TMEDIA-785?searchSessionId=29ec5713-71ea-43db-8cea-aa072212ddb6&searchObjectId=322933&searchContainerId=14230&searchContentType=issue

**Comment by JackHowa** [comment]
update for code reusability in the future

**Pull request closed without merging**
