### PR TITLE
TMEDIA-771 - Theme Switcher

### PR DESCRIPTION
**Pull request by matthewroach**
## Description

Add theme switcher to storybook and add initial theme files for news and commerce

## Jira Ticket

- [TMEDIA-771](https://arcpublishing.atlassian.net/browse/TMEDIA-771)

## Acceptance Criteria

* Update Storybook configs to be able to use the Sass library from Arc Themes Components
* When using Storybook there will be a dropdown that enables a consumer to toggle the theme of the rendered story to a given theme
* Set up two theme files that are used by the addon
    * News - This is the default option in the dropdown
    * Commerce

## Test Steps

1. Checkout this branch `git checkout TMEDIA-771-theme-switcher`
2. Update dependencies `npm i`
3. Run Storybook npm run storybook
4. Validate storybook controls now has a dropdown to switch themes

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
The theme files don't generate css variables at the moment right? I tried adding values and didn't see the css variables generated in the inspector. I've installed dependencies and saw the the theme components package was added

**Comment by matthewroach** [comment]
Correct - no blocks have the Sass library integrated yet - this is to put the storybook file in a place ready for block work

**Comment by JackHowa** [comment]
No, I understand no blocks have this. But I would expect the css variables to still be generated, right?

**Comment by matthewroach** [comment]
Storybook is doing this on the fly - so depending on what values you are setting it is likely you'll never see them in this instance

**Review by JackHowa — CHANGES_REQUESTED** [review]
Not able to verify that the themes are actually switching. I see the switcher. If I had variables like, 



```
@use "@wpmedia/arc-themes-components/scss" with (
	$tokens: (
		default: (
			components: (
				f: (
					color: red,
				),
			),
		),
	)
);

```
I would expect to see them generated similar to how theme components does in screenshot below

Screen Shot 2022-03-25 at 09 50 03

**Comment by matthewroach** [comment]
@JackHowa - Nice find, it was an issue with the dependency versions in use in this repository - I've updated the code now and you should see it worked as you describe

**Review by JackHowa — APPROVED** [review]
Cool! Working as expected. Nice work. Can switch themes and see css vars available when I set a dummy one on one theme 

Screen Shot 2022-03-25 at 10 46 43

**Review by JackHowa — APPROVED** [review]
Nice work. working as expected

**Pull request merged**
