### PR TITLE
TMEDIA-83 - Use queryly's minified JavaScript file

### PR DESCRIPTION
**Pull request by matthewroach**
## Description

Update script tag to use minified JavaScript file for queryly

## Jira Ticket
- [TMEDIA-83](https://arcpublishing.atlassian.net/browse/TMEDIA-83)

## Acceptance Criteria

1. Given I am Chrome Lighthouse
    * When I scan a Theme site page
    * Then I can see the Queryly JS is minified

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout TMEDIA-83-queryly-minified-js `
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/default-output-block`
3. Load homepage - http://localhost/pf/homepage/?_website=the-gazette
4. Verify the JavaScript file for queryly is using the .min.js version

### Before

TMEDIA-83-before

### After

TMEDIA-83-after

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [X] Confirmed all the test steps a reviewer will follow above are working.
- [X] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [X] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [X] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [X] Confirmed this PR has unit test files
  - [X] Ran `npm run test`, made sure all tests are passing
- [X] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by JackHowa — APPROVED** [review]
Working as expected. Great testing instructions 

Screen Shot 2021-04-01 at 09 09 29
Screen Shot 2021-04-01 at 09 08 57

**Comment by JackHowa** [comment]
is the goal for this not be seen in the main thread minimize? if so, I wonder if we can defer this 

Screen Shot 2021-04-01 at 09 11 42

**Comment by matthewroach** [comment]
> is the goal for this not be seen in the main thread minimize? if so, I wonder if we can defer this
> 
> Screen Shot 2021-04-01 at 09 11 42

I don't believe we can defer this - unless queryly tell us as there is other queryly code that runs inline that would be executed before the script is run and queryly wouldn't work

**Comment by JackHowa** [comment]
@matthewroach yeah no worries, I was getting issues trying it out quickly

**Comment by JackHowa** [comment]
@matthewroach this works as expected if we wanted it. I can make it into an issue or something

```
const querylyCode = (querylyId, querylyOrg, pageType) => {
  const querylyInit = `
    window.addEventListener('DOMContentLoaded', (event) => {
      queryly.init("${querylyId}", document.querySelectorAll("#fusion-app"));
    });
  `;
  return (
    <>
      <script data-integration="queryly" src="https://www.queryly.com/js/queryly.v4.min.js" defer />
      <script data-integration="queryly" dangerouslySetInnerHTML={{ __html: querylyInit }} />
      { pageType === 'queryly-search'
        ? <script data-integration="queryly" src={`https://www.queryly.com/js/${querylyOrg}-advanced-search.js`} />
        : null}
    </>
  );
};
```

Screen Shot 2021-04-01 at 09 46 59
Screen Shot 2021-04-01 at 09 47 09

**Pull request merged**
