### PR TITLE
Removed 'pos' targeting value from ads-block

### PR DESCRIPTION
**Pull request by vinnie-olsen**
## Description
Removed 'pos' targeting value from ads-block

## Jira Ticket
- [PEN-1223](https://arcpublishing.atlassian.net/browse/PEN-1223)

## Acceptance Criteria
`pos` targeting param should be removed but `position` should still be present

## Test Steps
1. In `Fusion-News-Theme` repo, checkout `master` & `git pull`
2. After checking out this feature branch in `fusion-news-theme-blocks`, run `rm -rf ./node_modules && npx lerna clean && npm i && npx lerna bootstrap && cd blocks/header-nav-chain-block && npm i && cd ../..`
3. Run `npx fusion start -f -l @wpmedia/header-nav-chain-block` in `Fusion-News-Theme`
4. Open homepage in PB editor and make sure two instances of `Google Ad` feature with a type of `leaderboard_large` are added to the page. 
5. Add a couple other instances of other ad types (doesn't really matter which types) - then stage & publish.
6. Open http://localhost/pf/homepage/?_website=the-sun in a new tab
7. Open Chrome DevTools `Network` tab and filter by `dfp`
8. Find the requests for the `leaderboard_large` ad calls and look for the `prev_scp` param (under query string params)
9. There should no longer be a `pos` param but there **should** be `position` params. The first of the `leaderboard_large` instances should have a `position` of `1` and the second instance should have a `position` of `2`.
10. Check the other ad requests to ensure they have a `position` param

### Before
Ad calls included `pos` targeting value in DFP request

### After
Ads no longer include the `pos` targeting value in DFP requests

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [X] Confirmed all the test steps above are working
- [X] Confirmed there are no linter errors
- [X] Confirmed this PR has reasonable code coverage
  - [X] Confirmed this PR has unit test files
  - [X] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [X] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
`Run npx fusion start -f -l @wpmedia/header-nav-chain-block in Fusion-News-Theme` should be ads-block, right? @vinnie-olsen 


image

**Comment by JackHowa** [comment]
looks good 
Screen Shot 2020-11-13 at 10 21 12
Screen Shot 2020-11-13 at 10 20 54

**Comment by JackHowa** [comment]
I think this is right: 

```
There should no longer be a pos param but there should be position params. The first of the leaderboard_large instances should have a position of 1 and the second instance should have a position of 2.

**Review by JackHowa — APPROVED** [review]
Good instructions!

**Comment by JackHowa** [comment]
Screen Shot 2020-11-13 at 10 15 59

**Comment by JackHowa** [comment]
Screen Shot 2020-11-13 at 10 23 57
don't see position so I think this is good

**Comment by vinnie-olsen** [comment]
@JackHowa ahh yess good call it was `@wpmedia/ads-block` but looks like you inferred that correctly 🙂 Yes those network screenshots look correct to me!

**Comment by vinnie-olsen** [comment]
Thanks for reviewing @JackHowa !

**Pull request merged**
