### PR TITLE
PEN-1594 Ability to use See More button when using Collections content source

### PR DESCRIPTION
**Pull request by ktran-wizeline**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
_Information about what you changed for this PR_
This PR fixing the issue see more button on result-list feature not working when configured to use **content-api-collections**. 
**Root cause:**  The main story [PEN-488](https://arcpublishing.atlassian.net/browse/PEN-488) not planing to support content-api-collections. It's only mentioned about see more content from stories on a Tags/Section/Author. With some investigation, I figured out that content-api-collections does not support the response with pagination like the other content api, let's see two important properties: **count** and **next** in story feed query response
Collection responses:
image

Story feed query responses:
image

**Technical approach:**
Option 1: Request content api team adding the property that supporting pagination( count, next )
Option 2: Update result-list-block implementation supported pagination (THIS PR DOES)
Option 3: Because collection api response only has maximum 20 items per collection, we don't need to pagination on it. Update documentation to let the user know about this behavior when using result-list-block

image

## Jira Ticket
- [PEN-1594](https://arcpublishing.atlassian.net/browse/PEN-1594)

## Acceptance Criteria
_copy from ticket_
What should be happening
Clicking the read more button portion of the results-list block should load more stories when that block is configured with the content-api-collections content source.

## Test Steps
- Add test steps a reviewer must complete to test this PR
1. In Fusion-News-Theme repo, checkout master & git pull
2. After checking out this feature branch in fusion-news-theme-blocks, run rm -rf ./node_modules && npx lerna clean && npm i && npx lerna bootstrap && cd blocks/header-nav-chain-block && npm i && cd ../..
3. Run: npx fusion start -f -l @wpmedia/results-list-block
4. Create a page then add the feature results-list-block and configure content-api-collections for testing

### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

https://user-images.githubusercontent.com/61674931/103264587-bba9ce80-49dd-11eb-8ce8-7031b58699e0.mov

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working. 
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by beltrancaliz** [comment]
@ktran-wizeline should this fix be applied to the search results list block or will that be a different ticket?

**Comment by beltrancaliz** [comment]
The mock file you included is over 42 KLOC, could we reduce it or is everything on that file necessary for mocking the collections api response?

**Comment by ktran-wizeline** [comment]
> @ktran-wizeline should this fix be applied to the search results list block or will that be a different ticket?
@beltrancaliz 
Yes, this fix applied to search result list block, the issue only happening when configured using content-api-collections. Pls see my technical approach define in description for more details

**Comment by beltrancaliz** [comment]
> > @ktran-wizeline should this fix be applied to the search results list block or will that be a different ticket?
> > @beltrancaliz
> > Yes, this fix applied to search result list block, the issue only happening when configured using content-api-collections. Pls see my technical approach define in description for more details

@ktran-wizeline I don't see it being applied to the search results list

**Comment by ktran-wizeline** [comment]
> > > @ktran-wizeline should this fix be applied to the search results list block or will that be a different ticket?
> > > @beltrancaliz
> > > Yes, this fix applied to search result list block, the issue only happening when configured using content-api-collections. Pls see my technical approach define in description for more details
> 
> @ktran-wizeline I don't see it being applied to the search results list

Sorry, I mean result list block. It not search result list block :( sorry for confusion!

**Comment by beltrancaliz** [comment]
> > > > @ktran-wizeline should this fix be applied to the search results list block or will that be a different ticket?
> > > > @beltrancaliz
> > > > Yes, this fix applied to search result list block, the issue only happening when configured using content-api-collections. Pls see my technical approach define in description for more details
> > 
> > 
> > @ktran-wizeline I don't see it being applied to the search results list
> 
> Sorry, I mean result list block. It not search result list block :( sorry for confusion!

so back to the original question, should this fix be applied to the search results list block in this PR as well or will that be a different ticket?

**Comment by ktran-wizeline** [comment]
> > > > > @ktran-wizeline should this fix be applied to the search results list block or will that be a different ticket?
> > > > > @beltrancaliz
> > > > > Yes, this fix applied to search result list block, the issue only happening when configured using content-api-collections. Pls see my technical approach define in description for more details
> > > 
> > > 
> > > @ktran-wizeline I don't see it being applied to the search results list
> > 
> > 
> > Sorry, I mean result list block. It not search result list block :( sorry for confusion!
> 
> so back to the original question, should this fix be applied to the search results list block in this PR as well or will that be a different ticket?

I just get confirm from Sara that we're not support pagination on search result list block. Thank you @beltrancaliz

**Comment by ktran-wizeline** [comment]
> The mock file you included is over 42 KLOC, could we reduce it or is everything on that file necessary for mocking the collections api response?

I completed the refactoring

**Review by beltrancaliz — APPROVED** [review]

**Comment by ktran-wizeline** [comment]
@LukeMason Could you please take a look on this pull request description. Because content api collection has a limitation that did not return the total number of items in our collection. So, we could not know when it should see "see more" button on every request.

Another option is always show "see more" button until the next request return null/empty. But this will need to update our requirement relates to pagination behavior.

**Comment by LukeMason** [comment]
Another option is to always request one more item than you will show and if you get it then show the "show more" button. Ex
if page size is 10 always request 11 items and then show 10 + a show more button if there is an 11th item. This will also give you one item overlap to help check for duplicates.

**Comment by ktran-wizeline** [comment]
but when configure the page size 20 (AKA 21), the response will return error: "message": "size request too large. size must be less than or equal to 20

**Pull request merged**
