### PR TITLE
TMEDIA-746 : Medium Manual Promo Block

### PR DESCRIPTION
**Pull request by ecarlisle**
## Description

Convert Medium Manual Promo Block

## Jira Ticket

- [TMEDIA-746](https://arcpublishing.atlassian.net/browse/TMEDIA-746)

## Test Steps

Use Chromatic for Visual updates

## Dependencies or Side Effects

https://github.com/WPMedia/arc-themes-feature-pack/pull/288

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by JackHowa — APPROVED** [review]
Working as expected -- matches behavior described

**Comment by JackHowa** [comment]
Needs https://github.com/WPMedia/arc-themes-manifests/pull/93 for manifest update

**Review by JackHowa — DISMISSED** [review]
This doesn't look like it's working as expected: wouldn't the description be up closer to the headline? also, it appears as though there's no horizontal space between the image and the title 

Screen Shot 2022-07-06 at 09 53 03

**Comment by JackHowa** [comment]
@haganka addressed feedback in the feedback pr https://github.com/WPMedia/arc-themes-blocks/pull/1407

**Comment by haganka** [comment]
@JackHowa approved those changes - thanks! @ecarlisle Let me know when they are reflected in this PR and I can approve here as well

**Comment by JackHowa** [comment]
is this still ready for design qa? looks like this can be merged @ecarlisle

**Comment by JackHowa** [comment]
Looks like Kelly removed the dqa. ready to merge? @ecarlisle

**Pull request merged**
