### PR TITLE
Tmedia 741 video in place fix

### PR DESCRIPTION
**Pull request by malavikakoppula**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description

PlayVideoInPlace should not have video icon and spacing around separator

## Jira Ticket

- [TMEDIA-TMEDIA-741-video-in-place-fix](https://arcpublishing.atlassian.net/browse/TMEDIA-741-video-in-place-fix)

## Acceptance Criteria

PlayVideoInPlace should not have video icon and spacing around separator

## Before
Screen Shot 2022-08-29 at 9 22 09 AM

## After
Screen Shot 2022-08-30 at 3 35 32 PM

Screen Shot 2022-08-30 at 3 35 45 PM

## Test Steps

1. Checkout this branch `git checkout TMEDIA-741-play-video-in-place-fix`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/large-promo-block`
3. Configure large-promo Block to use _id : CTAR7XCGLBCAXCHLJ6D5CZEGUA

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by matthewroach — DISMISSED** [review]

**Comment by JackHowa** [comment]
I shouldn't need to run with global phrases or large-manual-promo linked locally, right? Looking at the test instructions

`npx fusion start -f -l @wpmedia/large-manual-promo-block,@wpmedia/global-phrases-block`. Oh and `Configure Short-author-bio Block to use _id : CTAR7XCGLBCAXCHLJ6D5CZEGUA`
Screen Shot 2022-08-31 at 08 43 39

I only see changes in the large promo. I'll test locally with `npx fusion start -f -l @wpmedia/large-promo-block`, right?

**Comment by JackHowa** [comment]
Looks like the same bug is happening as before. I would expect for the chromatic to have the icon on the image, right? 

Screen Shot 2022-08-31 at 08 46 15

**Review by JackHowa — CHANGES_REQUESTED** [review]
Chromatic does not look like what's expected. The icon is not on the image: it's below the image

**Comment by malavikakoppula** [comment]
> I shouldn't need to run with global phrases or large-manual-promo linked locally, right? Looking at the test instructions
> 
> `npx fusion start -f -l @wpmedia/large-manual-promo-block,@wpmedia/global-phrases-block`. Oh and `Configure Short-author-bio Block to use _id : CTAR7XCGLBCAXCHLJ6D5CZEGUA` Screen Shot 2022-08-31 at 08 43 39
> 
> I only see changes in the large promo. I'll test locally with `npx fusion start -f -l @wpmedia/large-promo-block`, right?

Yes that works too.

**Comment by matthewroach** [comment]
@JackHowa Story is now fixed

**Review by JackHowa — APPROVED** [review]
Looks good in chromatic now! In the future, make sure your test instructions match the block being linked @malavikakoppula 

Thanks @matthewroach

**Pull request merged**
