### PR TITLE
TMEDIA 379 storybook for resutls list

### PR DESCRIPTION
**Pull request by JackHowa**
## Description
Storybook for results list 

## Jira Ticket
- [TMEDIA-379](https://arcpublishing.atlassian.net/browse/TMEDIA-379)

## Acceptance Criteria
Cover options for block results list 

## Test Steps
- look at generated storybook in the pr checks button and validate options 

### Before
- no sb coverage

### After
- sb coverage 

Screen Shot 2021-07-26 at 14 29 09

## Dependencies or Side Effects
- Used arc proptypes to ensure it works with sb

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by matthewroach** [comment]
Is there a reason we are showing broken images? The result list should fallback to use the fallback image from blocks.json - we should mock that intended behaviour with the needed data set up

**Review by matthewroach — CHANGES_REQUESTED** [review]
The results list shouldn't show broken images

**Comment by JackHowa** [comment]
> Is there a reason we are showing broken images? The result list should fallback to use the fallback image from blocks.json - we should mock that intended behaviour with the needed data set up

gotcha thanks will look into how we're doing this elsewhere @matthewroach

**Comment by JackHowa** [comment]
Updated thanks for setting this up as well 
Screen Shot 2021-07-27 at 09 38 53

**Comment by JackHowa** [comment]
updated with unique placeholder 

Screen Shot 2021-07-27 at 09 55 07

**Review by matthewroach — APPROVED** [review]
Thanks for the update @JackHowa

**Pull request merged**
