### PR TITLE
THEMES-1280 Gallery + Lead Art (mobile) | Update autoplay, progress indicator, carousel, and close controls in focus (expand) view

### PR DESCRIPTION
**Pull request by GioLopWP**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description

- Sets styles for expanding/full-screen view for lead-art, article-body-gallery, gallery-block

## Jira Ticket

- [THEMES-1280](https://arcpublishing.atlassian.net/browse/THEMES-1280)

## Acceptance Criteria

GIVEN I am a Media Site User, WHEN I expand a gallery, THEN:

- Styling is consistent with v2 designs on expanded gallery
- progress indicator (x of x)
- captions
- carousel controls (><) are removed to avoid duplication
- close 'x' control 

Note: the close control is currently not displaying on lead art, but is on the gallery block where style changes are needed (see examples above)

This should apply to gallery lead art as well as the gallery block

## Test Steps

- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout THEMES-1280`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/article-body-block,@wpmedia/gallery-block,@wpmedia/lead-art-block`
3. Iterate with the described blocks for example in "http://localhost/pf/all-blocks-test-ta/?_website=daily-intelligencer"

### After

Lead-art:
1-lead-art-default
2-lead-art-full-screen

Gallery-block:
3-gallery-block-default
4-gallery-block-full-screen

Article-body-gallery:
5-article-body-gallery-default
6-article-body-gallery-full-screen

## Dependencies or Side Effects

_Examples of dependencies or side effects are:_

- Manifest pr for new block:
- Feature pack pr for local development:
https://github.com/WPMedia/arc-themes-feature-pack/pull/464
- Dependency on another PR that needs to be merged at the same time:

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-1280]: https://arcpublishing.atlassian.net/browse/THEMES-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by vgalatro — APPROVED** [review]
This all looks good! Approving, but this is still a draft PR so I'm not sure if it will go through.

**Comment by vgalatro** [comment]
Ok the approval did go through, but this still needs to be changed to a regular PR.

**Comment by pardistaherzadeh** [comment]
@GioLopWP Looks good to me.

**Comment by pardistaherzadeh** [comment]
Looks good to me. @GioLopWP

**Pull request merged**
