### PR TITLE
TMEDIA 708: Use subs subtitle rather than duplicating title

### PR DESCRIPTION
**Pull request by JackHowa**
## Description

Use subheadline data not headline data

## Jira Ticket

- [TMEDIA-708](https://arcpublishing.atlassian.net/browse/TMEDIA-708)

## Acceptance Criteria
Actual Behavior
Subheadline is displaying the headline text.

Expected Behavior
Subheadline should be displaying the subheadline text.
## Test Steps

1. Checkout this branch `git checkout TMEDIA-708-sub-headline-subs`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/subscriptions-block`
3. Create page with an Offer on it
4. See data not duplicated 

Screen Shot 2022-03-21 at 14 49 20
Screen Shot 2022-03-21 at 14 48 30

### Before

dup headlines
Screen Shot 2022-03-21 at 14 53 32

### After
Screen Shot 2022-03-21 at 14 48 30

## Dependencies or Side Effects

- none

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by matthewroach — APPROVED** [review]

**Comment by matthewroach** [comment]
I understand this is a simple change for the wrong key being used, so I've marked this as approved - but we do have a failing check with the test coverage now we are running tests only on change set. What's the effort to bring the coverage up?

**Comment by JackHowa** [comment]
I initially was stumped how to improve the test coverage until I found that it may be due to changeset coverage checks.

with changeset coverage checking, the OfferCard does not have 100% test coverage
Screen Shot 2022-03-22 at 09 09 33

with checking all coverage, the OfferCard does have 100% coverage 
Screen Shot 2022-03-22 at 09 09 24


similar story with useOffer
Screen Shot 2022-03-22 at 09 11 50

**Comment by JackHowa** [comment]
I suppose I could write a test in those other tests to potentially trigger a more accurate changeset. I can timebox this before merging @matthewroach

**Comment by JackHowa** [comment]
Cool, removed the unnecessary mock for OfferCard. Then added more coverage by mocking url search params for 100% coverage with offer itself. @matthewroach 

Is this ok from a testing perspective? I know we talked about this being ok to merge; just wanted to check.

**Comment by matthewroach** [comment]
@JackHowa I am happy with the changes

**Pull request merged**
