### PR TITLE
PEN-1650: Fix spacing on Top Table List

### PR DESCRIPTION
**Pull request by npak243**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
Fix spacing issues on Top Table List
- Extra large: the space between the headline and the image is too big
- Large and medium: the headline and photo don’t align
- Medium: the space between the headline and description is too big

## Jira Ticket
- [PEN-1650](https://arcpublishing.atlassian.net/browse/PEN-1650)

## Test Steps
Open `All blocks` with `the sun` pages built in dev environment.

### Before
image

image

### After
image

image

## Dependencies or Side Effects
NO

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working. 
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist 
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr. 
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by beltrancaliz** [comment]
@npak243 please address the  stylelint errors when you have a chance

**Comment by npak243** [comment]
@beltrancaliz : I have fixed all stylelint issues already :).

**Comment by beltrancaliz** [comment]
> @beltrancaliz : I have fixed all stylelint issues already :).

weird... i'm still seeing these on my end

image

**Comment by npak243** [comment]
I think that the problem may come from the `force push` action and github doesn't remove this comment line. However, my PR has passed all checks now.
image

**Review by shk172 — APPROVED** [review]

**Pull request merged**
