### PR TITLE
Flex fix for left aligned logo

### PR DESCRIPTION
**Pull request by brentmiller1973**
## Description
Prevent left aligned logo from overlapping hamburger menu (especially when a centered nav is placed in the center of the header (eg https://www.wsbtv.com/).

## Jira Ticket
[- [TMEDIA-](https://arcpublishing.atlassian.net/browse/TMEDIA-)](https://arcpublishing.atlassian.net/browse/TMEDIA-610)

## Acceptance Criteria
CMG have reported an issue with their logo overlapping the Sections Menu button.

It looks to be a combination of CMG's set up that's not full accounted for in theme blocks, they have some custom widgets in the right hand side of the navigation that is requiring set widths and as space becomes a premium it's being taking from areas that it shouldn't (which we can fix).

We need to ensure block elements maintain their space, this can be done by applying flex-shrink: 0 CSS property to the .news-theme-navigation-container .nav-left selector

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout tmedia-614-header-nav-chain`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/shared-styles,@wpmedia/header-nav-block`
3. Update homepage so that the logo is left aligned:
image
4. View published homepage.  Not much to test on our demo sites, but ensure proper responsiveness occurs from desktop to mobile

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ x] Confirmed all the test steps a reviewer will follow above are working.
- [x ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x ] Confirmed this PR has unit test files
  - [x ] Ran `npm run test`, made sure all tests are passing

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
hmm seems to be working as expected; it's hard to tell without real test cases. but I wonder if this will be a problem for other alignments and growth. how was this tested? 

before 

https://user-images.githubusercontent.com/5950956/152854612-7a596bb1-5720-4356-ac89-ec299bc6fd10.mov

after 

https://user-images.githubusercontent.com/5950956/152854647-95884fd1-717b-4e7e-9aa7-025f01598558.mov

btw I slowed down the animations with the animation tab in dev tools 

Screen Shot 2022-02-07 at 13 05 52

**Comment by brentmiller1973** [comment]
@JackHowa Testing was sort of unconventional, but basically copied the center nav (`nav.horizontal-links-bar`) from https://www.wsbtv.com/ and inserted it into my local homepage and verified

**Comment by JackHowa** [comment]
@visionbegin can you look at maybe replicating this issue with storybook for header-nav-chain? I'd also be curious if this will affect the right area as well? 

If this is something custom on their end that we can't replicate, then it'd be hard for us to maintain this fix.

**Review by matthewroach — CHANGES_REQUESTED** [review]
Based on your comment @visionbegin that you needed to replicate the horizontal links bar content for testing - you are able to replicate this in storybook easy enough. You can configure what data is used for the horizontal links bar in the chain by changing the prop `horizontalLinksHierarchy` on the stories to match that of a mocked response using the value `threeLinks` will output three links in a story.

We will likely need to add an additional viewport value to ensure we are catch the intersection of where this issue is occurring. I'd set up the story to replicate the issue first to allow chromatic to get a snapshot of the issue before we the fix is applied, that way we can validate we have a way to replicate the issue

**Comment by brentmiller1973** [comment]
@JackHowa , @matthewroach Added storybook test that replicates the issue that was being seen on WSBTV.  I took a snapshot before and after the fix.  Here are the two snapshots:

Before:
https://5f91e4721ccaba0022a10782-ljzqhtgcmu.chromatic.com/?id=chains-header-nav-block--left-logo-with-links&viewMode=story

After:
https://5f91e4721ccaba0022a10782-btqbzdgvcw.chromatic.com/?id=chains-header-nav-block--left-logo-with-links&viewMode=story

**Review by matthewroach — APPROVED** [review]

**Comment by matthewroach** [comment]
@visionbegin This was closed instead of merged? Was there a reason for closing vs merging?

**Pull request merged**
