### PR TITLE
PEN-1689: Regression on Results List Block styling

### PR DESCRIPTION
**Pull request by vinnie-olsen**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
Fix for Results List Block regression that was causing images to take up 50% width

## Jira Ticket
- [PEN-1689](https://arcpublishing.atlassian.net/browse/PEN-1689)

## Acceptance Criteria
Should match Zeplin designs https://app.zeplin.io/project/5ea04773df4e1b7ae81167f8/screen/5ea04bb4401a867be62a2743

## Test Steps
1. In `Fusion-News-Theme` repo, checkout `master` & `git pull`
2. After checking out this feature branch in `fusion-news-theme-blocks`, run `rm -rf ./node_modules && npx lerna clean && npm i && npx lerna bootstrap && cd blocks/header-nav-chain-block && npm i && cd ../..`
3. Run `npx fusion start -f -l @wpmedia/results-list-block,@wpmedia/shared-styles` in `Fusion-News-Theme`
4. Open a test page in PB editor and add a Results List Block to the page. Configure it to use `story-feed-query` for content with a query of `type:story`.
5. Stage, publish, open in separate tab
6. You should see that images on desktop breakpoint now take up 35% of the list item width instead of 50%

### Before
Image on Results List Block list items were taking up 50% width (see https://corecomponents.arcpublishing.com/pf/tags/beaches/?_website=dagen for an example)

### After
Image on Result List Block list items are now taking up only 35% of the item width

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [X] Confirmed all the test steps a reviewer will follow above are working. 
- [X] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [X] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [X] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [X] Confirmed this PR has unit test files
  - [X] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [X] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist 
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr. 
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
looking now, pulling it down. surprised this is happening now

**Comment by JackHowa** [comment]
is this intentional? trying to look at the breakpoints. looks like we largely accomplished the goal for desktop 

working as expected 
Screen Shot 2021-01-26 at 10 32 51


not quite working, not totally sure (with width breakpoint). what do you think @vinnie-olsen ?
Screen Shot 2021-01-26 at 10 34 42

**Review by JackHowa — APPROVED** [review]
added a question, but looks like intended goal is done

**Comment by vinnie-olsen** [comment]
@JackHowa yep the only breakpoint that should be affected by the this change is desktop 🙂  The mobile styling should be unaffected and when I checked it locally against what's currently in the corecomponents env, it looked the same to me. It looks like the mobile view from your screenshot doesn't have padding on the sides. Is that the issue that you're seeing? And does it only render like that when you size the window down or does it maintain that after reloading with the viewport already set to a mobile size?

**Pull request merged**
