### PR TITLE
Placeholder Image - Images size updates

### PR DESCRIPTION
**Pull request by matthewroach**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description

Update placeholder image block to have a medium size image and remove large promo from specify a specific size. This allows for a single placeholder image size to be used for all blocks to avoid downloading multiple sizes of the same image

## Jira Ticket
- [TMEDIA-](https://arcpublishing.atlassian.net/browse/TMEDIA-)

## Acceptance Criteria
_copy from ticket_

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout image-native-lazy-load`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/shared-styles,@wpmedia/large-promo-block,@wpmedia/placeholder-image-block`
3. Validate placeholder images still render
4. Validate large promo does not request a different size placeholder image when a composer story does not have any promo images to show

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
to test placeholder improvements, right?

`npx fusion start -f -l @wpmedia/shared-styles,@wpmedia/large-promo-block,@wpmedia/placeholder-image-block,@wpmedia/top-table-list-block `

**Review by JackHowa — DISMISSED** [review]
using fallback dimensions for promos, currently only large

**Comment by JackHowa** [comment]
I guess once this is implemented across all promos, the hit of loading one larger placeholder will be better than loading many smaller ones

**Comment by matthewroach** [comment]
> I guess once this is implemented across all promos, the hit of loading one larger placeholder will be better than loading many smaller ones

This is applied across all promo's as the change was applied to the common promo image component

**Review by JackHowa — APPROVED** [review]
I see placeholders as expected and only one default image fetched

**Pull request merged**
