### PR TITLE
[PEN-1464] Opt into new thumbor param compression

### PR DESCRIPTION
**Pull request by jgrosspietsch**
## Description
Honestly have no idea why we're doing this "param compression" thing or why there's so much resizer logic in the blocks that that should be in the SDK but hey tickets are tickets.

The engine SDK is going to have some functionality that makes "param compression" something you need to opt into. This PR has changes that make sure we opt into it.

## Jira Ticket
- [PEN-1464](https://arcpublishing.atlassian.net/browse/PEN-1464)

## Test Steps
Look at some of our test pages and make sure the images are resized. 🤷‍♀️ 

### Before

...?

### After

...!

## Dependencies or Side Effects
Requires the SDK changes [here](https://github.com/WPMedia/engine-theme-sdk/pull/119) so keep that in mind when testing.

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps above are working
- [x] Confirmed there are no linter errors
- [x] Confirmed this PR has reasonable code coverage
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
@jgrosspietsch this should be against beta branch

**Comment by jgrosspietsch** [comment]
> @jgrosspietsch this should be against beta branch

It's on `beta` now.

**Comment by JackHowa** [comment]
cool, let me know if you found this. still would be kind of judging this blind https://github.com/WPMedia/engine-theme-sdk/pull/119#issuecomment-726187235

**Review by brentmiller1973 — APPROVED** [review]
Looks good to me Joe, must have been a pain...thanks for doing this

**Pull request merged**
