### PR TITLE
Pen 802 small promo image position 10 23

### PR DESCRIPTION
**Pull request by amyerz**
## Description
- Update small promo item to adjust image position using customfields
- blocks includes are top-table-list, small-manual-promo and small-promo
- the existing resizer error may caused the images in promo blocks to render incorrectly. Please refer PR https://github.com/WPMedia/fusion-news-theme-blocks/pull/515 for adjustment for testing

## Jira Ticket
- [PEN-802](https://arcpublishing.atlassian.net/browse/PEN-802)

## Acceptance Criteria
- A new Custom Field called Image Position is introduced. It should have the following options in a select menu

## Test Steps
- create a new page on your local (e.g. small-promo-test)
- add the following blocks to your page (top-table-list, small-manual-promo, and small-promo)

**TOP TABLE LIST TEST:**
- in top-table-list, update the customfields as the followings:
Screen Shot 2020-10-25 at 5 40 58 PM
- by default, the dropdown for the image position should be "Image Right"
- test the following screensize, image combination and image position

Top  table List |   |   |   |  
-- | -- | -- | -- | --
  |   |   |   |  
Desktop |   |   |   |  
Story per row :1 |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:3 | | |  | 
3:2 |  |  |  | 
16:09 |  |  |  | 
  |   |   |   |  
Story per row :2 |   |   |   |  
Image Ratio | Image Right | Image Left | Image Bottom | Image Above
4:3 |  |  |  | 
16:9 |  |  |  | 
3:2 |  |  |  | 
  |   |   |   |  
Tablet (Ipad) |   |   |   |  
Story per row: 1 |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:3 |  |  |  | 
3:2 |  |  |  | 
16:9 |  |  |  | 
  |   |   |   |  
Story per row: 2 |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:3 |  |  |  | 
3:2 |  |  |  | 
16:9 |  |  |  | 
  |   |   |   |  
Mobile (iphone x) |   |   |   |  
Story per row: 1 |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:3 |  |  |  | 
3:2 |  |  |  | 
16:9 |  |  |  | 
  |   |   |   |  
Story per row: 2 |   |   |   |  
Image Ratio |   |   |   |  
4:3 |  |  |  | 
3:2 |  |  |  | 
16:9 |  |  |  | 
---

**Small Manual Promo:**
- update the customfields based on the followings:
e.g. imageUrl: https://arc-anglerfish-arc2-prod-corecomponents.s3.amazonaws.com/public/ROWVW4VI5ZEJ7ISJNYEMVQ5YTE.png
Screen Shot 2020-10-25 at 5 52 26 PM

- by default, the dropdown for the image position should be "Image Right"
- test the following screensize, image combination and image position

Small Manual  |   |   |   |  
-- | -- | -- | -- | --
Desktop |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:3 |  |  |  | 
3:2 |  |  |  | 
16:9 |  |  |  | 
  |   |   |   |  
Tablet |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:03 |  |  |  | 
3:02 |  |  |  | 
16:09 |  |  |  | 
  |   |   |   |  
Mobile |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:03 |  |  |  | 
3:02 |  |  |  | 
16:09 |  |  |  | 
---

**Small Promo:**
- update the customfields based on the followings:
- use any article id, e.g. PWXE4DONCNHI7LY4MOIGSOEUP4
Screen Shot 2020-10-25 at 5 49 49 PM
- by default, the dropdown for the image position should be "Image Right"
- test the following screensize, image combination and image position

Small Promo |   |   |   |  
-- | -- | -- | -- | --
Desktop |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:3 |  |  |  | 
3:2 |  |  |  | 
16:9 |  |  |  | 
  |   |   |   |  
Tablet |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:03 |  |  |  | 
3:02 |  |  |  | 
16:09 |  |  |  | 
  |   |   |   |  
Mobile |   |   |   |  
Image Ratio | Image Right | Image Left | Image Below | Image Above
4:03 |  |  |  | 
3:02 |  |  |  | 
16:09 |  |  |  | 

---
- [ ] after the above visual test, run `npm run lint` and `npx run test:coverage` to check the code changes

### Before
no imagePosition customfields available under small promo, small manual promo and top table list blocks

### After
- changing imagePosition dropdown:
Image Below:
image-below

Image Above:
image-above jpg

Image Left:
image-left jpg

Image Right:
image-right

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps above are working
- [x] Confirmed there are no linter errors
- [x] Confirmed this PR has reasonable code coverage
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
@amyerz when I ran `npm t`, there were snapshots written. can you make sure those changes are pushed 

Screen Shot 2020-10-27 at 15 56 40

**Comment by amyerz** [comment]
@JackHowa  apologize for the missing file. added 3 snapshots in https://github.com/WPMedia/fusion-news-theme-blocks/pull/516/commits/cdfe42ff4fc686083e9c3ca6a337d87ff7caa82d

**Comment by beltrancaliz** [comment]
@amyerz could you please add these new fields to the affected block's configurable params under the block's README

**Review by beltrancaliz — APPROVED** [review]

**Comment by LukeMason** [comment]
@amyerz do you mind resolving these conflicts? Once that is done feel free to merge or let me or @visionbegin know know and we can merge for you.

**Review by brentmiller1973 — APPROVED** [review]

**Pull request merged**
