### PR TITLE
Block spacing updates bmiller

### PR DESCRIPTION
**Pull request by brentmiller1973**
This PR accompanies this pr from the news-theme-css repo https://github.com/WPMedia/news-theme-css/pull/51. It is part of this ticket: https://arcpublishing.atlassian.net/browse/PEN-1475.

At the core of this PR was modifications to these files:  blocks/card-list-block/features/card-list/card-list.scss, blocks/numbered-list-block/features/numbered-list/numbered-list.scss and blocks/simple-list-block/features/simple-list/simple-list.scss

However, after trying to push this branch, the git hook that runs tests ran and I had over 75 test failures.  Some investigation turned up that Lerna is not installing the peer dependencies (`npx lerna bootstrap`) that are needed for the tests to execute properly.  

As a temporary solution I followed these steps:

1)  I installed this library globally: `sudo npm i -g recursive-install `
2) In my terminal changed my working directory to /blocks
3) Ran the command `npm-recursive-install` to iterate through all the block packages and install their dependencies.
4) Ran `npm run test` and verified all test passes.
5) Git added and committed all modified package.json and package-lock.json files
6) Successfully pushed this branch up.

Needless to say, this sucks.  There is some chatter that the new beta version of npm (7.3.0) helps Lerna with installing peer deps.  I tried installing it `sudo npm i -g npm@next-7 => 7.3.0` but that didn't help, so I reverted npm back to version latest (6.14.10).  We'll have to dig deeper into this and find a more elegant solution.

### CODE REVIEW

**Review by RobinGiannattasio — APPROVED** [review]
Looks good from a code perspective, once I was able to sift through all those package.json and locks. Oh my! I have high hopes for the lerna fix,  but that's gonna be another nightmare of a clean up, me thinks. Good job finding a work around!

**Review by JackHowa — CHANGES_REQUESTED** [review]
Not sure I totally understand the package-lock issues, may need to look into this fix more. but I have a working version of your branch with test instructions as well. hope you don't get this notification too early ;)

**Comment by JackHowa** [comment]
yo Brent! when you're up, check out WPMedia/fusion-news-theme-blocks#643. I looked into the test issues. if that's ok, we can merge my branch. I reverted some of the package updates as well

**Comment by JackHowa** [comment]
fixed this in favor of cleaner merge https://github.com/WPMedia/fusion-news-theme-blocks/pull/643

**Pull request closed without merging**
