### PR TITLE
Fix general conditions for visibility of promo components.

### PR DESCRIPTION
**Pull request by nschubach**
## Description
Updated conditionals surrounding render components involving the image (and video) tags in promotional items and in top table list promos.

## Jira Ticket
- [TMEDIA-219](https://arcpublishing.atlassian.net/browse/TMEDIA-219)

## Acceptance Criteria
Content should not change except in the case where images are the only inclusion.  In such a case, those should now be rendered.

## Test Steps
- Visit `http://localhost/pagebuilder/editor/curate?p=p0ciQAinp2VIRr&v=vFzdS81np2VIRr`
- Select the first promo item 'Extra Large Manual Promo – Arc Block'
- Open the Show Promo Elements option
  image
- Deselect all but the image and verify that it still shows up without the other elements
  image
- Repeat for each promo block type
- Also verify the 'Table Top List Block' using the same pattern.
 

1. Checkout this branch `git checkout 219-promo-block-visibility`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/extra-large-manual-promo-block,@wpmedia/extra-large-promo-block,@wpmedia/large-manual-promo-block,@wpmedia/large-promo-block,@wpmedia/medium-manual-promo-block,@wpmedia/medium-promo-block,@wpmedia/top-table-list-block`

### Before
Selecting only the image would show nothing
image

### After
Selecting only the image will now show the image
image

## Author Checklist
- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
@nschubach looks like there's some conflicts. can you resolve them?

**Comment by nschubach** [comment]
> @nschubach looks like there's some conflicts. can you resolve them?

@JackHowa Already on it ;)

**Comment by JackHowa** [comment]
huh seems to be working for the promos but not for the top table list options? I'm linking the blocks specified `@wpmedia/extra-large-manual-promo-block,@wpmedia/extra-large-promo-block,@wpmedia/large-manual-promo-block,@wpmedia/large-promo-block,@wpmedia/medium-manual-promo-block,@wpmedia/medium-promo-block,@wpmedia/top-table-list-block`. I've fetched and up to date with your branch

Screen Shot 2021-05-13 at 10 34 08

**Review by JackHowa — CHANGES_REQUESTED** [review]
weird I'm not seeing any top table list in my pb editor at all. I can look into this more. can you show me what you're seeing for top table list options in a screenshot? 

-----

Working as expected for manual and promo blocks xl - sm. Doesn't seem to be working for top table list options. I can still see headlines and overlines, for instance, when I should only see the image for the top-table list's promo options

**Review by JackHowa — APPROVED** [review]
nice work @nschubach ! 

validated top table list functionality on another page http://localhost/pagebuilder/editor/curate?p=pFJuLTQKesshoEms&v=vGwv0Kzy3tshoEms

Screen Shot 2021-05-13 at 10 43 59

**Comment by JackHowa** [comment]
@nschubach lgtm!

**Pull request merged**
