### PR TITLE
Tmedia 369 storybook short author bio

### PR DESCRIPTION
**Pull request by JackHowa**
## Description
Add visual documentation for short author options

## Jira Ticket
- [TMEDIA-369](https://arcpublishing.atlassian.net/secure/RapidBoard.jspa?rapidView=875&modal=detail&selectedIssue=TMEDIA-369&assignee=5e387d6a1b1d910e5dfd7a9b)

## Acceptance Criteria
- Cover different data setups for short author

## Test Steps
- See changes in chromatic

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
Screen Shot 2021-08-03 at 11 08 23
can review by clicking details here

**Comment by nschubach** [comment]
Some of these are missing images:
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb798
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb799

Are blank...
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb79a
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb79b
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a0
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a1
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a7
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a8

or have some concerning differences (spacing difference?):

https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7d1
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7d2
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7d5
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7d6
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7d7
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7d8
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7db
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7dc
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7dd
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7de

**Comment by nschubach** [comment]
The missing images and blank ones could easily be data related fro the storybook entries... but I'm not sure why the added padding is in the last set.  Do you know?

**Comment by JackHowa** [comment]
yep without resized params, the image won't show. that's deliberate. should I clarify that the image won't show in the story? @nschubach 

Screen Shot 2021-08-03 at 13 51 44

**Comment by nschubach** [comment]
> yep without resized params, the image won't show. that's deliberate. should I clarify that the image won't show in the story? @nschubach
> 
> Screen Shot 2021-08-03 at 13 51 44

Oh, ok, that one makes sense.  I should probably read the title more often.  (feels a little broken though, maybe a ticket for removing the image or something...)

**Comment by JackHowa** [comment]
interesting, it looks like there were registered changes to the full author bio? when only short author bio should have changed

Screen Shot 2021-08-03 at 13 59 13

**Comment by nschubach** [comment]
> interesting, it looks like there were registered changes to the full author bio? when only short author bio should have changed
> 
> Screen Shot 2021-08-03 at 13 59 13

Do you think this is just something that has slipped through from another change?  I see no reason why your changes would impact this.

**Comment by JackHowa** [comment]
This seems like either a bug or undocumented side effect of the component itself. also some of these stories would seem to be blank like zero authors. I can delete those. were you able to see what the story string attached to the output is? @nschubach  https://www.chromatic.com/build?appId=5f91e4721ccaba0022a10782&number=654

> 

Are blank...
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb79a
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb79b
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a0
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a1
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a7
https://www.chromatic.com/test?appId=5f91e4721ccaba0022a10782&id=610836aa2383ea003b3fb7a8

**Comment by nschubach** [comment]
Sorry, if there's a zero author, that's likely valid, re-checking.

**Comment by JackHowa** [comment]
if no bio or description then the component will not show deliberately: 


```jsx
    // If the author doesn't have a description, then do not add them to the list
    // Also check for their bio, which means that they are a staff
    if (
      author.description
            && author.description.length > 0
            && original
            && original.bio
            && original.bio.length > 0
    ) {
```

**Comment by JackHowa** [comment]
updated as well to include the short and full author dependency in the shared-styles package

**Comment by JackHowa** [comment]
updated as well to include the short and full author dependency in the shared-styles package

**Review by nschubach — APPROVED** [review]
Nice!

**Pull request merged**
