### PR TITLE
THEMES-1474: Input display bug

### PR DESCRIPTION
**Pull request by vgalatro**
## Description

_Information about what you changed for this PR_

## Jira Ticket

- [THEMES-1474](https://arcpublishing.atlassian.net/browse/THEMES-1474)

## Acceptance Criteria

The search box should meet the margin size and cover the search icon.

## Test Steps

1. Checkout this branch `git checkout THEMES-1474`
2. Checkout `arc-themes-components` branch `git checkout THEMES-1474`
3. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/search-results-list-block,@wpmedia/identity-block`
4. Add the search results list block to a page, and make sure the input is sized appropriately.
5. Then check the Identity blocks that use the input component (Log in, sign up, account management) and make sure their inputs are still sized correctly according to the Figma docs.

### Before

Screenshot 2023-11-02 at 1 31 34 PM

### After

Screenshot 2023-11-02 at 1 31 16 PM

## Dependencies or Side Effects

- arc-themes-components PR: https://github.com/WPMedia/arc-themes-components/pull/217

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-1474]: https://arcpublishing.atlassian.net/browse/THEMES-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nschubach** [comment]
Can we update: https://github.com/WPMedia/arc-themes-blocks/blob/arc-themes-release-version-2.1.1/.storybook/themes/news.scss

**Comment by vgalatro** [comment]
@nschubach , do you know the last time that file was updated? I'm seeing nearly every line change when pasting in the newest build from my local. And it's not just the missing commas either (since prettier was removed from the feature pack).

**Comment by vgalatro** [comment]
I see why there's so many changes now, didn't realize the quotes on the properties were also being removed by prettier.

**Review by blakeganderson — APPROVED** [review]
LGTM

**Pull request merged**
