### PR TITLE
[THEMES-1464] Fixed Results-list Lazyload: false

### PR DESCRIPTION
**Pull request by malavikakoppula**
## Description

When looking at this page: http://williamreed-foodnavigator-asia-sandbox.web.arc-cdn.net/Headlines/  The Results List is added with lazyload: false, but it still lazy loads. 

## Jira Ticket

- [THEMES-1464](https://arcpublishing.atlassian.net/browse/THEMES-1464)

## Acceptance Criteria

Results List is not lazy loading, when disabled

## Test Steps

1. Checkout this branch `git checkout THEMES-1464`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/results-list-block`
3. Uncheck Lazy Load in custom fields
4. Inspect for image to be `loading="eager"`

### Before
Screenshot 2024-03-05 at 12 02 26 PM

### After
Screenshot 2024-03-05 at 12 03 06 PM

Screenshot 2024-03-12 at 1 59 16 PM

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

[THEMES-1464]: https://arcpublishing.atlassian.net/browse/THEMES-1464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nschubach** [comment]
This only seems to pass along the lazyload flag to the images.  I don't believe that was the issue, was it?

**Comment by vgalatro** [comment]
No, that was an issue with it, but the main was is that this block does not render server side at all.

**Comment by rmbrntt** [comment]
Ok, so it still isn't SSR. 

@malavikakoppula can you confirm the SSR works and has no errors?

**Comment by nschubach** [comment]
👍 
Previous:
image
This:
image

**Review by nschubach — APPROVED** [review]
Looks good!

**Pull request merged**
