### PR TITLE
Themes 1198.5 social icons redux

### PR DESCRIPTION
**Pull request by cedric066**
**This PR goes with an `arc-themes-feature pack` PR (you can find it [here](https://github.com/WPMedia/arc-themes-feature-pack/pull/435)) and an `arc-themes-components` PR (you can find it [here](https://github.com/WPMedia/arc-themes-components/pull/195))**

## Description

During testing, it was discovered that the [original version of 1198](https://github.com/WPMedia/arc-themes-blocks/pull/1686) had incorrect acceptance criteria (based on the [hover states audit](https://paper.dropbox.com/doc/Themes-hover-states-audit--B400R8DxsjiVy0YImyMBZ0B4Ag-JyHvxHuZttlIfj5BzjTI3)). The goal of this ticket is to revert those changes and to adjust some other social icons in OOTB blocks. I made the following changes:

* `share-bar-block/themes/news.json`:
    * Reverted the social icons from `$color primary` back to the original brand colors
    * Removed the hover states from the social icons, so they now have no hover effects
* `blocks/footer-block`:
    * `_index.scss`:
        * Because I removed the `icon-hover` selector (see [the `arc-themes-components` PR](https://github.com/WPMedia/arc-themes-components/pull/195)), I had to add a hover selector in the index file instead
        * This allowed me to add a "footer-social-links-hover" class in `news.json`, which allowed the footer social icons to have a hover state
    * `themes/news.json`:
        * Used the additions to `_index.scss` to make the icons be `$color-primary` when hovered over
        * Now, the social icons in the footer have a hover state
* In the original iteration of 1198, I changed the `icon` component to give it a hover state. However, I noticed when working on this ticket that those changes to `icon` were breaking the behavior of the other social icons. Every social icon had a black hover state. To fix this, I removed the `icon-hover` selector
    * This has a separate PR that can be found [here](https://github.com/WPMedia/arc-themes-components/pull/195)
    * The changes are in `_index.scss` in the `icon` component
    * This is needed to make the styling changes function correctly
* Because of the changes to the `icon` component, no changes were required for the full and short author bio blocks. They already behave as expected
* I updated the news styling in `./storybook/themes` to reflect the changes made to the block's `themes` directory
* As a result of these changes, some changes were also automatically made to the `site-styles` directory in `arc-themes-feature-pack`
    * You can find a link to that PR [here](https://github.com/WPMedia/arc-themes-feature-pack/pull/435)
    * These are needed to run this code

## Jira Ticket

[THEMES-1198.5](https://arcpublishing.atlassian.net/browse/THEMES-1198)

## Acceptance Criteria

1. Social icons hover styles are applied on the
    * Full/short author bio blocks
    * Footer:
        * Rest: `$color-primary`
        * Hover: `$color-primary-hover`
2. Social share bar icon colors are reverted back to the default social brand colors: [Themes Block Styling 2.0](https://www.figma.com/file/NBjMF1v4mzwv9jkn7NEq9V/Themes-Block-Styling-2.0?type=design&node-id=11034-153194&mode=design&t=9pcaFWyyoC1DlsqT-0)

## Test Steps

1. Checkout this branch: `git checkout THEMES-1198.5-social-icons-redux`
2. Run fusion repo with linked blocks `npx fusion start -f -l  @wpmedia/footer-block,@wpmedia/share-bar-block,@wpmedia/full-author-bio-block,@wpmedia/author-bio-block`
3. Open your local PageBuilder instance and open the 'All Blocks-Test-TA-Sandbox' page. This page has a Share Bar and Footer block
    * Verify that the Share Bar's social icons match the social brand colors (as described here [here](https://www.figma.com/file/NBjMF1v4mzwv9jkn7NEq9V/Themes-Block-Styling-2.0?type=design&node-id=10924-193717&mode=design&t=x8RijdUbLLFCR5at-0))
    * Make sure the Share Bar's social icons have no hover effects
4. Create a new page. This will be used to test the Footer, Short Author Bio, and the Full Author bio
    * Select any layout you want. I used the Right Rail
    * Place a Short Author Bio block, Full Author Bio block, and a Footer block
        * No configurations need to be changed for the bio blocks
        * For the footer, go to the 'Configure Content' dropdown. Set Navigation to 'navigation-hierarchy', set Content Source to 'site-service-hierarchy', and set the hierarchy to 'footer' (then click 'Update').
        * Under the Global Content section of the Curate tab, set the Content Source to 'content-api', set the _id to '43UU6MCQERAMRPTD23B3CEXE7E' (you can use another if you want), then click 'Update'. Now, the page should have all three blocks populated with the correct content
5. Verify that the social icons in the Short Author Bio block, Full Author Bio block, and Footer block are `$color-primary`  (black right now) at rest and `$color-primary-hover` (`#3842355` right now) when hovered over. There is a separate ticket to update `color-primary` and `color-primary-hover` to the correct values (in [here](https://www.figma.com/file/vWVGgZfZVBdSX7ACo3kmjr/Enhanced-Styling-Design-System?type=design&node-id=7053-58820&mode=design&t=6aRneJpzubFSEfHc-0)).

### Before

**Only pay attention to the social media icons**

#### Share Bar

https://github.com/WPMedia/arc-themes-blocks/assets/103296586/b0e9880b-716e-4d43-b69e-260b73bd5979

*These changes were made in the original version of 1198*

#### Footer

Screenshot 2023-07-07 at 9 52 39 AM

There is no hover effect on these icons

#### Short Author Bio

Screenshot 2023-07-11 at 1 33 17 PM

#### Full Author Bio

Screenshot 2023-07-11 at 1 32 57 PM

#### Share Bar

https://github.com/WPMedia/arc-themes-blocks/assets/103296586/83e30e1a-0578-4f79-a30d-97c56a288303

*This is reverted back to the pre-1198 styling*

#### Footer

https://github.com/WPMedia/arc-themes-blocks/assets/103296586/c733f09d-ce06-464c-bcfa-1b0ffdd2c4f1

#### Short Author Bio

https://github.com/WPMedia/arc-themes-blocks/assets/103296586/1eeb84ac-6c01-4663-b4c5-dc8289497df6

#### Full Author Bio

https://github.com/WPMedia/arc-themes-blocks/assets/103296586/90e1bdee-db2e-4065-b0f7-4fee492f8beb

## Dependencies or Side Effects

This PR is dependent on some changes to `arc-themes-components`. The PR is [here](https://github.com/WPMedia/arc-themes-components/pull/195). It's also dependent on some changes to `arc-themes-feature-pack`. The PR is [here](https://github.com/WPMedia/arc-themes-feature-pack/pull/435).

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by blakeganderson — DISMISSED** [review]
LGTM 👍

**Comment by cedric066** [comment]
Pardis noticed that I missed the brand-color-based hover states for the share bar block. I added a commit that fixes this

The hover colors can be found [in here](https://www.figma.com/file/NBjMF1v4mzwv9jkn7NEq9V/Themes-Block-Styling-2.0?type=design&node-id=11034-153194&mode=design&t=USr6jihP79nCP7yP-0)

**Review by blakeganderson — APPROVED** [review]
LGTM 👍

**Comment by pardistaherzadeh** [comment]
LGTM. Ready to be merged. @cedric066

**Pull request merged**
