### PR TITLE
Update tests coverage (wip)

### PR DESCRIPTION
**Pull request by kascote**
WIP

# What does this implement or fix?
- try to complete tests on blocks 
- increase test coverage
- remove warnings from test run

# How was this tested?
- test written

### CODE REVIEW

**Review by JackHowa — COMMENTED** [review]
Looking good so far! excited to see where this goes

**Comment by RobinGiannattasio** [comment]
As part of the work in [PEN-1265](https://arcpublishing.atlassian.net/browse/PEN-1265) to standardize branches, we are deprecating the `staging` branch in favor of `canary`. So, I switched the base of this PR. Thanks!

**Comment by JackHowa** [comment]
closing this pr but I'd definitely try to incorporate some of these improvments @kascote in another branch

**Comment by kascote** [comment]
I think will be better to take some code from this big PR and make individual PR for each block, that will be more easy to review and apply. what do you think @JackHowa ?

**Comment by JackHowa** [comment]
definitely @kascote

**Pull request closed without merging**
