### PR TITLE
TMEDIA-347/large_promo_refactor

### PR DESCRIPTION
**Pull request by farleyawapo**
**If you have not filled out the checklist below, the pr is not ready for review.**

## Description
Refactor for `large-promo` and `large-manual-promo`.
the presentational code for `large-promo` will likely be able to be used in other blocks as well.

## Jira Ticket
- [TMEDIA-347](https://arcpublishing.atlassian.net/browse/TMEDIA-347)

## Acceptance Criteria
Refactor code between large promos blocks.
Store presentational logic in shared-styles.
Adjust tests as needed.

## Test Steps
- Add test steps a reviewer must complete to test this PR

1. Checkout this branch `git checkout TMEDIA-347/large_promo_refactor `
2. Run storybook: `npm run storybook`
3. Do a visual test to make `large-promo` and `large-manual-promo` blocks look the same locally as they do here: https://canary--5f91e4721ccaba0022a10782.chromatic.com/

## Effect Of Changes
All visuals should stay the same. This is simply a refactor.

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by nschubach — DISMISSED** [review]
Looks good!

**Comment by nschubach** [comment]
I just pushed a change that removed some unnecessary mocks.  I think we need to fix these tests, but If you think it's too much for these refactors, maybe we should open a ticket to approach that.  What do you think @RobinGiannattasio ?  Should these be resolved with this story or do we open up another backlog item?

**Comment by nschubach** [comment]
Some history may be warranted here... the tests had to be moved from the old block location, but in simplifying the block we also simplify the testing around them by exposing some mock data as params.  Pulling the tests from the old brings along some cruft that I think should be cleaned up and mocks created so we aren't testing things that this depends on and have their own tests.  So, I kind of agree that there's a pretty big ask to "rework the tests" but I don't know if it's appropriate to resize this bigger to make it acceptable or open a new story to resolve the test burden.

**Comment by RobinGiannattasio** [comment]
Hey all!

Thanks for the context, @nschubach.

I think we can approach this in a few ways
1) Upping the points in this ticket to reflect the appropriate scope of work and have it all done
2) Still up the points of the ticket, but create a subtask to reflect the tests and open up in a new PR
3) Create a new ticket that we can also bring in to this sprint and point that appropriately

I'm leaning towards 1 or 2, because they both will keep this PR more focused (as well as a subsequent PR)

I agree that this seems like an appropriate time to address this testing tech debt, however, because we want to make sure we aren't building on outdated patterns.

**Review by nschubach — DISMISSED** [review]
Approval under the protest that we open a story to revisit tests. ;)

**Review by nschubach — APPROVED** [review]

**Pull request merged**
