### PR TITLE
TMEDIA-253: Change all promos to render null if there is no content instead of a …

### PR DESCRIPTION
**Pull request by nschubach**
## Description
Do not render promos if there is no content

## Jira Ticket
- [TMEDIA-253](https://arcpublishing.atlassian.net/browse/TMEDIA-253)

## Acceptance Criteria
If no content is present for one of these promo blocks, then nothing should render on the page (including the issues described in this ticket: no fallback promo image, nor spacing around it)

## Test Steps
1. Checkout this branch `git checkout TMEDIA-253-do-not-render-no-content-promos`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/extra-large-manual-promo-block,@wpmedia/extra-large-promo-block,@wpmedia/large-manual-promo-block,@wpmedia/large-promo-block,@wpmedia/medium-manual-promo-block,@wpmedia/medium-promo-block,@wpmedia/shared-styles,@wpmedia/shared-styles,@wpmedia/shared-styles,@wpmedia/small-manual-promo-block,@wpmedia/small-promo-block`
3. Load up http://localhost/pagebuilder/editor/curate?p=pPdo2UO0eFD57Prs&v=vhpcVNxjdFD57Prs
4. Note the space above the promotions on the right bar:
image
5. Add a promo item with no/invalid content specified:
image
image
6. Verify that it does not change the layout:
image
7. Repeat for extra-large, medium, and small

### Before
When adding a promo with no content or invalid content, the page would include the image with a replacement button:
image

### After
No content will show up unless properly configured:
image

## Dependencies or Side Effects
N/A

## Author Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist
_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by matthewroach — CHANGES_REQUESTED** [review]
When you conditional render with a `useContent` response any children elements that have `useContent` calls in them will never be picked up on the server side render, and will be pushed to the client side to fetch content. As promo blocks use `<PromoImage>` which has a server side `useContent` hook this is causing promo blocks that need to render the placeholder image to give 404 errors on the client side as it tries to use a server side only content call.

A test article to validate this is - /local/2021/06/08/a-workingstory/

Would we not wrap the checks in the content source source and query values being present?

**Comment by nschubach** [comment]
> When you conditional render with a `useContent` response any children elements that have `useContent` calls in them will never be picked up on the server side render, and will be pushed to the client side to fetch content. As promo blocks use `<PromoImage>` which has a server side `useContent` hook this is causing promo blocks that need to render the placeholder image to give 404 errors on the client side as it tries to use a server side only content call.
> 
> A test article to validate this is - /local/2021/06/08/a-workingstory/
> 
> Would we not wrap the checks in the content source source and query values being present?

I have tested this more than I care to talk about (but I have learned lots of things...) and I just don't see it loading on the client or giving 404 errors.

If I test http://localhost/pf/allpromo/?_website=the-gazette which has all the promos (not lazily loaded), this is my network call stack (no client side requests for data besides images, but those are all lazy).
image

My latest push cleans up some console warnings about contenteditable and moves the content check to a short circuit null render, but otherwise it's the same concept.

I'm not seeing any 404s in the above page.

If I pull up a page where I was getting 404s for some images: http://localhost/pf/homepage/?_website=dagen

Pre-this branch:
image

With this branch:
image

There is no difference in mechanical function.

(This was all performed with empty content promos contained in those pages)

**Comment by nschubach** [comment]
Updated test instructions for additional block updates (for contenteditable warning reduction)

**Review by matthewroach — APPROVED** [review]
Looks good to me 🎉

**Pull request merged**
