### PR TITLE
Remove order/order override

### PR DESCRIPTION
**Pull request by nschubach**
## Description

This just removes an override for the order/order requirement that we changed in https://github.com/WPMedia/arc-themes-blocks/pull/1302

### Testing

Ensure that the stylelint error is not appearing

### Before

Linting errors in stylelint would be thrown for ordering of the import.

### After

These errors should not exist.

## Dependencies or Side Effects

https://github.com/WPMedia/arc-themes-blocks/pull/1302

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
@nschubach for this, do you want me to disable the order-order rule?

**Comment by JackHowa** [comment]
@nschubach for this, do you want me to disable the order-order rule?

**Comment by nschubach** [comment]
@JackHowa I'm just waiting for the other PRs to merge, then this should pass.

**Review by JackHowa — APPROVED** [review]
looks good

**Pull request merged**
