### PR TITLE
PEN-423 Ads Block (wip)

### PR DESCRIPTION
**Pull request by ghost**
## Description
Added Ads Block

## Jira Ticket
- [PEN-423](https://arcpublishing.atlassian.net/browse/PEN-423)

## Acceptance Criteria
_copy from ticket_

## Test Steps
Coming Soon

### Before
_Example: When I clicked the search button, the button turned red._

[include screenshot or gif or link to video, storybook would be awesome]

### After
_Example: When I clicked the search button, the button turned green._

[include screenshot or gif or link to video, storybook would be awesome]

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps above are working
- [ ] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
added wip because it's still in development

**Comment by JackHowa** [comment]
@vinnie-olsen @nealmalkaniwapo -- is this still in progress? I see other ads work

**Comment by JackHowa** [comment]
looks like this is a duplicate of an existing pr #500. can reopen if not

**Comment by vinnie-olsen** [comment]
@JackHowa yep that's correct 👍  This is now a duplicate of https://github.com/WPMedia/fusion-news-theme-blocks/pull/500

**Pull request closed without merging**
