### PR TITLE
Tmedia 755 simple list block

### PR DESCRIPTION
**Pull request by annasherman**
Screen Shot 2022-08-02 at 10 19 29 AM

Change min-height to be on list-item element instead of top-level element so an empty block shows up with no height

### CODE REVIEW

**Comment by matthewroach** [comment]
@annasherman - What's with all the commits? Did you branch from a clean base branch?

**Comment by annasherman** [comment]
> @annasherman - What's with all the commits? Did you branch from a clean base branch?

No I accidentally used my old branch. I just pulled in main

**Review by malavikakoppula — COMMENTED** [review]
Title font-size in Desktop is 20px and in Default it's 18px. According to figma,  it's 20px in both views.
Screen Shot 2022-08-02 at 11 17 23 AM

**Comment by annasherman** [comment]
@malavikakoppula I think (hope) I addressed your comment with my change!

**Review by malavikakoppula — APPROVED** [review]
LGTM

**Comment by JackHowa** [comment]
ready for dqa @haganka

**Comment by matthewroach** [comment]
Can we clean up the history on this PR - we are going to end up creating duplicate commits on the head branch

**Comment by annasherman** [comment]
> Can we clean up the history on this PR - we are going to end up creating duplicate commits on the head branch

I will squash and merge and remove the duplicate commits

**Review by nschubach — APPROVED** [review]

**Pull request merged**
