### PR TITLE
TBRANDS-66 - Asset key change

### PR DESCRIPTION
**Pull request by matthewroach**
## Description

Update code to reflect asset key being removed and value being an array

This is going to branch - 2.0.2 as we want to include in upcoming release, there will be another PR to bring changes to 2.0.3 too

## Jira Ticket

- [TBRANDS-66](https://arcpublishing.atlassian.net/browse/TBRANDS-66)

## Test Steps

1. Checkout this branch `git checkout TBRANDS-66-asset-update`
2. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/product-featured-image-block,@wpmedia/product-gallery-block`
3. In a page with the Product Feature Image Block, and Product Gallery Block validate blocks render
    * When Arc Commerce content source (`commerce-product`) is set to use SKU `bounce-running-shoe`
    * And also validate product featured image is rendered when using data from Commerce API with SKU `themes-001`

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Comment by JackHowa** [comment]
Running with `npx fusion start -f -l @wpmedia/product-featured-image-block,@wpmedia/product-gallery-block,@wpmedia/commerce-product-content-source-block` as the commerce product source block is needed for the mock data  to validate `When Arc Commerce content source (commerce-product) is set to use SKU bounce-running-shoe
`

**Review by JackHowa — DISMISSED** [review]
Looks pretty good. AC working as expected.

```
When Arc Commerce content source (commerce-product) is set to use SKU bounce-running-shoe
And also validate product featured image is rendered when using data from Commerce API with SKU themes-001
```


Noticed error with the product gallery for at least the themes-001 

Screen Shot 2022-10-04 at 09 45 43

Screen Shot 2022-10-04 at 09 45 33

**Comment by matthewroach** [comment]
@JackHowa Added code to address the error you see

**Comment by JackHowa** [comment]
ok thanks -- will re-test @matthewroach

**Review by JackHowa — APPROVED** [review]
Working as expected with also no errors for themes-001

Screen Shot 2022-10-04 at 10 16 46

**Review by nschubach — APPROVED** [review]

**Pull request merged**
