### PR TITLE
TBRANDS-129 - Design review feedback

### PR DESCRIPTION
**Pull request by matthewroach**
## Description

Addressed the following items from design review

1. Icon within close button on hover should be white
2. When resizing the viewport the thumbnail images did not always observe the available height

## Jira Ticket

- [TBRANDS-129](https://arcpublishing.atlassian.net/browse/TBRANDS-129)

## Test Steps

1. Checkout this branch `git checkout TBRANDS-129-design-review-feedback`
2. Checkout the feature pack branch `TBRANDS-129-design-review-feedback`
3. Run fusion repo with linked blocks `npx fusion start -f -l @wpmedia/product-gallery-block`
4. Either using an existing page with the product gallery block / or creating a new page with the product gallery block
     * When clicking on a product gallery image in desktop viewports the focused view should appear and you can verify the two changes addressed
     * Hover over close button (top right) and verify icon is white
     * Resized the browsers height and see the thumbnails adjust based on available space 

## Dependencies or Side Effects

Feature Pack Pull Request - https://github.com/WPMedia/arc-themes-feature-pack/pull/360

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm run test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] Linting code actions have passed.
- [ ] Ran the code locally based on the test instructions.
  - [ ] I don’t think this is needed to be tested locally. For example, a padding style change (storybook?) or a logic change (write a test).
- [ ] I am a member of the engine theme team so that I can approve and merge this. If you're not on the team, you won't have access to approve and merge this pr.
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.

### CODE REVIEW

**Review by rmbrntt — DISMISSED** [review]
Icon color and size update looks good 
image

Verified the thumbnail issue as well.

**Comment by matthewroach** [comment]
@rmbrntt - I've made further changes to address the issue design reported with the inconsistent thumbnail bar

**Comment by rmbrntt** [comment]
Testing this out with the latest changes, I am able to repro Kelly's issue noted in the ticket regarding the top arrow not responding to clicks until the 3-4th so it doesn't appear resolved. 
```
I was able to replicate on Firefox and Chrome. Just opened FF and clicked through and was able to see the issue of trying to click the up arrow button with no response until 3rd or 4th click. Lmk if you or anyone else want to huddle today
```

How do you prefer to proceed? Merge and put it out for DQA still? As there are some other positive changes here, not sure if we want to keep holding this one up as it isn't necessarily introducing any new bugs (as far as I can test).

**Review by rmbrntt — DISMISSED** [review]
behavior on the thumbnails and arrow looking much improved, nice job

**Pull request merged**
