### PR TITLE
PEN-1527 Advertisement Label Display for mobile view

### PR DESCRIPTION
**Pull request by amyerz**
## Description
- update to hide advertisement label for right rail cube in mobile

## Jira Ticket
- [PEN-1527](https://arcpublishing.atlassian.net/browse/PEN-1527)

## Acceptance Criteria
- advertisement label should be hidden in mobile view for `Right rail cube` ad type

## Test Steps
- pull this branch locally, and run rm -rf ./node_modules && npx lerna clean && npm i && npx lerna bootstrap && cd blocks/header-nav-chain-block && npm i && cd ../..
- in `Fusion-New-Theme` repo, run `npx fusion start -f -l @wpmedia/ads-block@canary`
- once fusion started, create a new page with `right-rail` layout, and add the `Ad Block` to the `right rail` section
Screen Shot 2020-12-09 at 2 01 23 PM

- in the `Ad Block` customfield, select `Right Rail Cube` Type
Screen Shot 2020-12-09 at 2 01 41 PM

- stage and published the page
- in regular desktop view, you should be able to see the `Advertisement` label
- open chrome developer tool, and select to mobile view and refresh the page
- once the page is refreshed, the advertisement label should not be shown.

### Before
advertisement label for right rail cube rendered on mobile view even though no ad is rendered.

### After
advertisement label for right rail cube NO LONGER render on mobile view.

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps a reviewer will follow above are working. 
- [x] Confirmed there are no linter errors. Please run `npm run lint` to check for errors. Often, `npm run lint:fix` will fix those errors and warnings.
- [x] Confirmed this PR has reasonable code coverage. You can run `npm run test:coverage` to see your progress.
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm run test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by beltrancaliz** [comment]
@amyerz it looks like this PR has two changes: a README update, and a new unit test. Is there a main change of functionality that's missing to meet the acceptance criteria?

**Comment by amyerz** [comment]
@beltrancaliz  The readme updates was missing from PEN-1508 AC while remove the customfield.
https://arcpublishing.atlassian.net/browse/PEN-1508
As for the unit test, it's adding to showcase it's only display with desktop. the class --mobile no longer exist. Looks like some of my files wasn't in :-( let me double check again! sorry about the confusion!

**Comment by amyerz** [comment]
just check with Vinnie, and need to update scenarios on other ad types

**Comment by amyerz** [comment]
closing this PR for additional cases

**Pull request closed without merging**
