### PR TITLE
Suggestions for changes on author-bio-block

### PR DESCRIPTION
**Pull request by nschubach**
There were several changes I was going to suggest and it felt like I needed to make a PR change request for them...

* uncomment gap, and remove margins
* place gap on the wrapper, not the icons themselves
* set heading-level-6 on the author name per design
* set body-font-size-small on the description for mobile
* Author name used to be a `h4`, you made it a `Paragraph`... should be a `Heading` to continue that usage
* Cleaned up `Link`/`Icon` generation
* Use `Conditional` component to render the link around the author name instead of weird existing if conditionals
* Updated test to properly grab the author link
* Added `__author-name-link` as you were creating two elements previously that both had `__author-name` class nested

### CODE REVIEW

**Comment by malavikakoppula** [comment]
Lockfile is still present in the diff.

**Comment by JackHowa** [comment]
is this good to merge @malavikakoppula ? Good idea @nschubach  making a feedback pr

**Comment by malavikakoppula** [comment]
> Lockfile is still present in the diff.

No Jack. Lockfile is still present in the diff. It'll affect my PR.

**Review by JackHowa — APPROVED** [review]
This looks like an improvement based off your other work on the author bio block. Make sure your package-lock matches the base branch

**Comment by JackHowa** [comment]
Oh ok, that should be a quick fix! If you check out this branch, it could be good practice to fix this change

https://github.com/WPMedia/arc-themes-blocks/pull/1489#issuecomment-1228980243

**Comment by malavikakoppula** [comment]
> Oh ok, that should be a quick fix! If you check out this branch, it could be good practice to fix this change
> 
> [#1489 (comment)](https://github.com/WPMedia/arc-themes-blocks/pull/1489#issuecomment-1228980243)

Now, this PR is ready to merge.

**Pull request merged**
